#!/bin/bash

tituloInicio="| Visita Nuestra Comunidad - https://t.me/ArchLinuxCristo - by: Arcris v2.0 |"

titulo="| Instalación de ArchLinux en Español - https://t.me/ArchLinuxCristo |"



if ping -c 3 www.google.com &> /dev/null; then

clear
ping -c 5 www.google.com
echo ""
echo ""
echo ""
echo " ██████╗ ██████╗ ███╗   ██╗███████╗██╗  ██╗██╗ ██████╗ ███╗   ██╗";
echo "██╔════╝██╔═══██╗████╗  ██║██╔════╝╚██╗██╔╝██║██╔═══██╗████╗  ██║";
echo "██║     ██║   ██║██╔██╗ ██║█████╗   ╚███╔╝ ██║██║   ██║██╔██╗ ██║";
echo "██║     ██║   ██║██║╚██╗██║██╔══╝   ██╔██╗ ██║██║   ██║██║╚██╗██║";
echo "╚██████╗╚██████╔╝██║ ╚████║███████╗██╔╝ ██╗██║╚██████╔╝██║ ╚████║";
echo " ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝";
echo "                                                                 ";

echo "███████╗██╗  ██╗██╗████████╗ ██████╗ ███████╗ █████╗ ";
echo "██╔════╝╚██╗██╔╝██║╚══██╔══╝██╔═══██╗██╔════╝██╔══██╗";
echo "█████╗   ╚███╔╝ ██║   ██║   ██║   ██║███████╗███████║";
echo "██╔══╝   ██╔██╗ ██║   ██║   ██║   ██║╚════██║██╔══██║";
echo "███████╗██╔╝ ██╗██║   ██║   ╚██████╔╝███████║██║  ██║";
echo "╚══════╝╚═╝  ╚═╝╚═╝   ╚═╝    ╚═════╝ ╚══════╝╚═╝  ╚═╝";
echo "                                                     ";
echo ""
echo ""
echo "Cargando..."
sleep 5
#echo "Presiona ENTER para continuar..."
#read line

#Variable para zona horaria
clear
zonahorariaok=$(curl https://ipapi.co/timezone)
echo ""
echo "Cargando..."
clear


else
clear
echo ""
echo ""
echo ""
echo "██╗      █████╗      ██████╗ ██████╗ ███╗   ██╗███████╗██╗  ██╗██╗ ██████╗ ███╗   ██╗";
echo "██║     ██╔══██╗    ██╔════╝██╔═══██╗████╗  ██║██╔════╝╚██╗██╔╝██║██╔═══██╗████╗  ██║";
echo "██║     ███████║    ██║     ██║   ██║██╔██╗ ██║█████╗   ╚███╔╝ ██║██║   ██║██╔██╗ ██║";
echo "██║     ██╔══██║    ██║     ██║   ██║██║╚██╗██║██╔══╝   ██╔██╗ ██║██║   ██║██║╚██╗██║";
echo "███████╗██║  ██║    ╚██████╗╚██████╔╝██║ ╚████║███████╗██╔╝ ██╗██║╚██████╔╝██║ ╚████║";
echo "╚══════╝╚═╝  ╚═╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝";
echo "                                                                                     ";


echo "███████╗ █████╗ ██╗     ██╗      ██████╗ ";
echo "██╔════╝██╔══██╗██║     ██║     ██╔═══██╗";
echo "█████╗  ███████║██║     ██║     ██║   ██║";
echo "██╔══╝  ██╔══██║██║     ██║     ██║   ██║";
echo "██║     ██║  ██║███████╗███████╗╚██████╔╝";
echo "╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ";
echo "                                         ";
echo ""
echo ""
echo "Intenta conectarte a internet para continuar"
echo ""
sleep 5
#echo "Presiona ENTER para intentar nuevamente..."
#read line
exit

clear
fi



main () {

while true; do
choice=$(dialog --keep-tite --backtitle "$tituloInicio" --title "-| Arcris |-" \
--ok-label '*Seleccionar*' --nocancel --column-separator "|" --no-tags \
--menu "\nSeleccione una opción a continuación utilizando las teclas\n[FLECHA ARRIBA] / [FLECHA ABAJO] y [ESPACIO] o [ENTER]\
\nLas teclas alternativas también se pueden usar: [+], [-] y [TAB]. \n " 22 70 11 \
1 "1 USERS | Establecer Datos Personales" \
2 "2 TIMEZONE | Establecer la zona horaria del sistema" \
3 "3 LANGUAGE | Establecer el idioma del sistema" \
4 "4 SHELL | Establece la shell del sistema" \
5 "5 DISK | Particionar la unidad de instalación" \
6 "6 KERNEL | Establecer el kernel del sistema" \
7 "7 DRIVER VIDEO | Establecer el driver de video del sistema" \
8 "8 (DE) or (WM) | Establecer un Escritorio o Gestor de Ventanas" \
9 "9 EXTRA PROGRAMS | Selecciona programas extras - [ OPCIONAL ]" \
10 "> INSTALL | Instalar Arch Linux" \
11 "> EXIT | Salir del Script ArcriS" 3>&1 1>&2 2>&3)

case "$choice" in
"1")
;;


"2")


"3")

;;
## FIN DE LANGUAGE



"4") #SH

;;




"5")

;;

"6")
## INICIO DE KERNEL 


;;
### FIN KERNEL 



"7")
## INICIO DE DRIVER VIDEO
# MENSAJE 
dialog --backtitle "$titulo" \
--title "| Información |" \
--msgbox "\n> Si esta usando Maquina virtual la selección de Driver de Video es: \
\n  [Automatico] \n \
\n> Si esta usando Hardware real tiene dos opciones para seleccionar: \
\n  [Automatico] o [Manual] \n" 11 75

#Inicio de Video
virt=""
GPU=""
VM=false
VMbox=false
VMqemu=false

infovideo () {
clear
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "_"
echo -e ""
echo -e "\t\t\t         | Info Hardware de Video |          "
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
lspci -v | grep "VGA compatible controller" -A 9
echo ""
echo "Presiona [ENTER] para confirmar..."
read line
}


   




;;
## FIN DE DRIVER VIDEO


"8")
## INICIO DE (DE) or (WM)


;;
## FIN DE (DE) or (WM)



"9")
## INICIO DE EXTRA PROGRAMS

        TERMI=""
        UTIL=""
        AUDIO=""
        WEB=""
        REPRO=""
        OFFICE=""
        AP=""
        RS=""
        AUR=""
        AUR_DELETE=""
        programasextrasSI=false
        programasextrasNO=false




dialog --title "-| Programas Extras |-" --yesno "\n¿ Deseas instalar Programas extras en su sistema ?\n\nEsto puede tomar un poco más de tiempo\nTodas las descargas son de repo oficiales y de AUR" 9 55
case $? in
   0) 

#TERMINALES
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo"  \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --checklist "Terminal para tu sistema\n[ ESPACIO ] - Para marcar o desmarcar *" 17 70 20)
options=(1 "lxterminal" on    # any option can be set to default to "on"
         2 "tilix" off
         3 "xfce4-terminal" off
         4 "deepin-terminal" off
         5 "mate-terminal" off
         6 "terminator" off
         7 "sakura" off
         8 "alacritty" off
         9 "kitty" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            TERMI1="lxterminal"
            TERMINAL_condicion=true
            ;;
        2)
            TERMI2="tilix"
            TERMINAL_condicion=true
            ;;
        3)
            TERMI3="xfce4-terminal"
            TERMINAL_condicion=true
            ;;
        4)
            TERMI4="deepin-terminal"
            TERMINAL_condicion=true
            ;;
        
        5)
            TERMI5="mate-terminal"
            TERMINAL_condicion=true
            ;;

        6)
            TERMI6="terminator"
            TERMINAL_condicion=true
            ;;
               
        7)
            TERMI7="sakura"
            TERMINAL_condicion=true
            ;;   
        8)
            TERMI8="alacritty"
            TERMINAL_condicion=true
            ;;   
        9)
            TERMI9="kitty"
            TERMINAL_condicion=true
            ;;   
    esac
done
TERMI=" $TERMI1 $TERMI2 $TERMI3 $TERMI4 $TERMI5 $TERMI6 $TERMI7 $TERMI8 $TERMI9 "
#FINAL DE TERMINALES




#AUDIO
cmd=(dialog --no-collapse --cr-wrap --title "-| Audio del Sistema |-" --backtitle "$titulo"  \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --checklist "\nPulseAudio es para el usuario tradicional \
\nJack Audio es para Profesionales sin latencia \
\nAlsa Audio es para terminal sin Interfaz Gráfica\n \
\n[ ESPACIO ] - Para marcar o desmarcar *" 15 70 20)
options=(1 "Pulseaudio + Códecs de audio" on    # any option can be set to default to "on"
         2 "Jack2      + Códecs de audio" off
         3 "ALSA       + Códecs de audio" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AUDIO1="pulseaudio pulseaudio-alsa pavucontrol pamixer \
            pulseaudio-equalizer lib32-alsa-plugins lib32-libpulse pulseaudio-equalizer-ladspa"
            #https://wiki.archlinux.org/index.php/PulseAudio
            #pulseeffects libcanberra-pulse libcanberra-gstreamer
            ;;
        2)
            AUDIO2="realtime-privileges jack2 lib32-jack2 a2jmidid libffado python-dbus waf pro-audio lv2-plugins ladspa-plugins dssi-plugins vst-plugins"
            #https://wiki.archlinux.org/index.php/Professional_audio
            ;;
        3)
            AUDIO3="alsa-utils alsa-plugins alsa-oss alsa-firmware pamixer"
            #https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture
            ;;
    esac
done
AUDIO=" $AUDIO1 $AUDIO2 $AUDIO3 "

#FIN_AUDIO



#UTILIDADES
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo"  \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --checklist "Utilidades para tu sistema\n[ ESPACIO ] - Para marcar o desmarcar *" 18 70 20)
options=(1 "Lectura y formateo de discos incluido Android" on    # any option can be set to default to "on"
         2 "Compresión y Descompresión de archivos" on
         3 "Códecs de video, lectura de todos los formatos de vídeo" off
         4 "gufw - Firewall de red" off
         5 "hardinfo - Información del sistema y benchmark" off
         6 "gnome-disk-utility - Administrador de Discos" off
         7 "gparted - Administrador de Discos" off
         8 "bluez - Bluetooth" off
         9 "viewnior - Visor de Imagenes" off
         10 "gedit - Editor de Textos GTK" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
1)
UTIL1="android-file-transfer android-tools android-udev msmtp libmtp \
libcddb gvfs gvfs-afc gvfs-smb gvfs-gphoto2 gvfs-mtp gvfs-goa gvfs-nfs gvfs-google gst-libav \
dosfstools f2fs-tools exfat-utils ntfs-3g \
udftools nilfs-utils polkit gpart mtools cifs-utils"
;;
#   jfsutils btrfs-progs xfsprogs reiserfsprogs


2)
UTIL2="xarchiver unarchiver binutils gzip lha lrzip lzip lz4 p7zip tar xz \
bzip2 p7zip lbzip2 arj lzop cpio unrar unzip zstd zip lzip unarj zstd"
;;
3)
UTIL3="ffmpeg aom libde265 x265 x264 libmpeg2 xvidcore libtheora libvpx \
schroedinger sdl gstreamer gst-plugins-bad gst-plugins-base gst-plugins-base-libs \
gst-plugins-good gst-plugins-ugly xine-lib libdvdcss libdvdread dvd+rw-tools lame \
jasper libmng libraw libkdcraw vcdimager"
;;
4)
UTIL4="gufw"
;;

5)
UTIL5="hardinfo"
;;

6)
UTIL6="gnome-disk-utility"
;;

7)
UTIL7="gparted"
;;

8) blutudriverS=true
UTIL8="bluez bluez-utils pulseaudio-bluetooth"
;;

9)
UTIL9="viewnior"
;;   

10)
UTIL10="gedit"
;;   
    esac
done
UTIL="$UTIL1 $UTIL2 $UTIL3 $UTIL4 $UTIL5 $UTIL6 $UTIL7 $UTIL8 $UTIL9 $UTIL10 "

dialog --backtitle "$titulo" \
--title "-| Paquetes de Utilidades |-" --ok-label '*Confirmar*' --nocancel \
--msgbox "\n$UTIL" 15 73
#FINAL DE UTILIDADES




#REPRODUCTOR
sporitykey=false
REPRO_condicion=false
spotify_condicion=false

cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' \
--title "-| Reproductores Video y Audio |-" --checklist "\n[ ESPACIO ] - Para marcar o desmarcar *" 20 100 19)
options=(   1 "vlc" on
            2 "mpv" off
            3 "mplayer" off
            4 "nuclear-player-bin" off            
            5 "elisa" off
            6 "spotify" off
            7 "spotify-Sin-Anuncios-adblock" off
            8 "clementine" off
            9 "audacious" off
            10 "xplayer" off
            11 "rhythmbox" off
            12 "moc" off
            13 "cmus" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            REPRO1="vlc"
            REPRO_condicion=true
            ;;
        2)
            REPRO2="mpv"
            REPRO_condicion=true
            ;;
        3)
            REPRO3="mplayer"
            REPRO_condicion=true
            ;;
        4)
            REPRO4="nuclear-player-bin"
            REPRO_condicion=true
            ;;
        5)
            REPRO5="elisa"
            REPRO_condicion=true
            ;;
        6)
            REPRO6="spotify"
            REPRO_condicion=true
            spotify_condicion=true
            ;;
        7)
            REPRO7="spotify-adblock-linux"
            REPRO_condicion=true
            spotify_condicion=true
            ;;
        8)
            REPRO7="clementine"
            REPRO_condicion=true
            ;;
        9)
            REPRO8="audacious"
            REPRO_condicion=true
            ;;
        10)
            REPRO9="xplayer"
            REPRO_condicion=true
            ;;
        11)
            REPRO10="rhythmbox"
            REPRO_condicion=true
            ;;
        12)
            REPRO11="moc"
            REPRO_condicion=true
            ;;
        13)
            REPRO12="cmus"
            REPRO_condicion=true
            ;;
    esac
done
REPRO=" $REPRO1 $REPRO3 $REPRO4 $REPRO5 $REPRO6 $REPRO7 $REPRO8 $REPRO9 $REPRO10 $REPRO11 $REPRO12 $REPRO13 "
# FIN REPRODUCTOR




#NAVEGADORES
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --checklist "Seleeciona tu navegador web\n[ ESPACIO ] - Para marcar o desmarcar *" 15 100 19)
options=(1 "Firefox | Open source" on    # any option can be set to default to "on"
         2 "Chromium | Open source" off
         3 "Brave | AUR - Open source" off
         4 "Google Chrome | AUR - Proprietary browser" off         
         5 "Opera | Proprietary browser" off
         6 "Vivaldi | AUR - Proprietary browser" off
         7 "Tor-browser | AUR - Open source" off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            WEB1="firefox"
            WEB_condicion=true
            ;;
        2)
            WEB2="chromium"
            WEB_condicion=true
            ;;
        3)
            WEB3="brave-bin"
            WEB_condicion=true
            ;;
        4)
            WEB4="google-chrome"
            WEB_condicion=true
            ;;
        5)
            WEB5="opera"
            WEB_condicion=true
            ;;
        6)
            WEB6="vivaldi"
            WEB_condicion=true
            ;;
        7)
            WEB7="tor-browser"
            WEB_condicion=true
            tor_condicion=true
            ;; 
    esac
done
WEB=" $WEB1 $WEB2 $WEB3 $WEB4 $WEB5 $WEB6 $WEB7 "
# FIN NAVEGADORES








#OFFICE
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --checklist "Suite de Ofimática\n[ ESPACIO ] - Para marcar o desmarcar *" 11 70 14)
options=(    1 "LibreOffice | libreoffice-fresh" on
             2 "WPS Office | AUR - wps-office" off
             3 "SoftMaker Office | AUR - freeoffice " off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            OFFICE1="libreoffice-fresh libreoffice-fresh-es hunspell hunspell-es_es hunspell-es_any hyphen hyphen-es mythes-es"
            OFFICE_condicion=true
            ;;
        2)
            OFFICE3="wps-office ttf-wps-fonts hunspell hunspell-es_es hunspell-es_any"
            OFFICE_condicion=true
            ;;
        3)
            OFFICE4="freeoffice hunspell hunspell-es_es hunspell-es_any hyphen hyphen-es mythes-es"
            OFFICE_condicion=true
            ;;
    esac
done
OFFICE=" $OFFICE1 $OFFICE2 $OFFICE3 "
# FIN OFFICE




#Administrador de Procesos
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo"  --title "-| Administrador de Procesos |-" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --checklist "\n[ ESPACIO ] - Para marcar o desmarcar *\n " 15 70 20)
options=(1 "gnome-system-monitor" on
         2 "htop" on
         3 "gotop - AUR" off
         4 "gtop" off
         5 "bashtop" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AP1="gnome-system-monitor"
            AP_condicion=true
            ;;
        2)
            AP2="htop"
            AP_condicion=true
            ;;
        3)
            AP3="gotop"
            AP_condicion=true
            ;;
        4)
            AP4="gtop"
            AP_condicion=true
            ;;

        5)
            AP5="bashtop"
            AP_condicion=true
            ;;
            
            
    esac
done
AP=" $AP1 $AP2 $AP3 $AP4 $AP5 "
#FINAL DE Administrador de Procesos


#Redes Sociales
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo"  --title "-| Redes Sociales |-" \
--no-tags --ok-label '< Siguiente >' --column-separator "|" --cancel-label '< No deseo esto >' --checklist "\n[ ESPACIO ] - Para marcar o desmarcar *\n " 15 70 20)
options=(1 "Telegram | telegram-desktop" on
         2 "IGdm - AUR | App de chat de Instagram" off
         3 "Whatsapp - AUR | whatsapp-nativefier-dark" off
         4 "Facebook Messenger - AUR | caprine" off
         5 "Netflix - AUR | netflix-qdesktop" off
         6 "Skype - AUR | skypeforlinux-preview-bin" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            RS1="telegram-desktop aspell-es"
            RS_condicion=true
            ;;
        2)
            RS2="igdm-bin aspell-es"
            RS_condicion=true
            ;;
        3)
            RS3="whatsapp-nativefier-dark aspell-es"
            RS_condicion=true
            ;;
        4)
            RS4="caprine aspell-es"
            RS_condicion=true
            ;;    
        5)
            RS5="netflix-qdesktop aspell-es"
            RS_condicion=true
            ;;            
        6)
            RS6="skypeforlinux-preview-bin aspell-es"
            RS_condicion=true
            ;;
            
    esac
done
RS=" $RS1 $RS2 $RS3 $RS4 $RS5 $RS6 "
#FINAL DE Redes Sociales

#nombre_usuario=$(cat /etc/passwd | grep '/home' | cut -d: -f1)


aurherlp=false

dialog --title "-| AUR Helper |-" --backtitle "$titulo" --yesno "\n¿Desea un asistente para hacer descargas en Arch User Repository?" 7 70

case $? in
   0) #AUR
cmd=(dialog --no-collapse --cr-wrap --backtitle "$titulo"  --title "-| AUR Helper |-" \
--no-tags --ok-label '< Siguiente >' --column-separator "|" --cancel-label '< No deseo esto >' --checklist "\n[ ESPACIO ] - Para marcar o desmarcar *\n " 20 80 20)
options=(1 "yay | Terminal" on
         2 "trizen | Terminal" off
         3 "pikaur | Terminal" off
         4 "aurman | Terminal" off
         5 "pakku | Terminal" off
         6 "Pamac | Graphical" off
         7 "Octopi | Graphical" off
         8 "Cylon | Graphical" off
         9 "Argon | Graphical" off
         10 "Pakku GUI | Graphical" off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AUR1="yay-bin"
            AUR_condicion=true
            ;;
        2)
            AUR2="trizen"
            AUR_condicion=true
            ;;
        3)
            AUR3="pikaur"
            AUR_condicion=true
            ;;
        4)
            AUR4="aurman"
            AUR_condicion=true
            ;;    
        5)
            AUR5="pakku"
            AUR_condicion=true
            ;;            
        6)
            AUR6="pamac-aur"
            AUR_condicion=true
            AUR_pamac=true
            ;;
        7)
            AUR7="octopi"
            AUR_condicion=true
            ;; 
        8)
            AUR8="cylon"
            AUR_condicion=true
            ;;
        9)
            AUR9="argon"
            AUR_condicion=true
            ;; 
        10)
            AUR10="pakku-gui"
            AUR_condicion=true
            ;; 

    esac
done
AUR=" $AUR1 $AUR2 $AUR3 $AUR4 $AUR5 $AUR6 $AUR7 $AUR8 $AUR9 $AUR10 "
#FINAL DE AUR
;;
   1) AUR_DELETE="yay-bin"
        aurherlp=true
        ;;

   255) echo "[ESC] key pressed.";;
esac

programasextrasSI=true

;;
#SELECCIONO QUERER PROGRAMAS
   1) 
        TERMI=""
        UTIL=""
        AUDIO=""
        SH=""
        WEB=""
        REPRO=""
        OFFICE=""
        AP=""
        RS=""
        AUR=""
        AUR_DELETE=""
        programasextrasNO=true
        ;;
#SELECCIONO NO QUERER PROGRAMAS

   255) echo "Presiono la tecla [ESC]";;
esac

clear
;;
## FIN DE EXTRA PROGRAMS



"10")
## INICIO DE INSTALL

if [ "$finalInstall" == "true" ]; then

# MENSAJE 
dialog --backtitle "$titulo" \
--title "| Información |" \
--msgbox "\n> Inicia con la descarga de [base] y [base-devel] \
\n> Actualiza la lista de MirrorList a [reflector] \
\n> Descarga el Kernel Seleccionado \
\n> Luego configura todo lo seleccionado\n \
\n> Arcris solo es un asistente para una instalación rápida \
\n> Arcris usa repositorios oficiales de Arch Linux y AUR \
\n> El tiempo de instalación depende de los paquetes seleccionado \
\n> Al terminar el equipo se reiniciara con su sistema instalado" 15 73

clear
echo ""
echo "Cargando..."
echo -e "\n\n\n\n\n\n\n\n\n\n\n"
echo ""
echo -e '\033[38;2;255;0;02m'
echo " █████╗ ██████╗  ██████╗██████╗ ██╗███████╗";
echo "██╔══██╗██╔══██╗██╔════╝██╔══██╗██║██╔════╝";
echo "███████║██████╔╝██║     ██████╔╝██║███████╗";
echo "██╔══██║██╔══██╗██║     ██╔══██╗██║╚════██║";
echo "██║  ██║██║  ██║╚██████╗██║  ██║██║███████║";
echo "╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚══════╝";
echo "                                           ";
echo -e '\033[m'
sleep 2



#echo -e "\t\t\t| Actualizando Hora Actual en LiveCD |"
#printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
#echo -e ""
#sleep 2
timedatectl set-timezone $zonahorariaok
#pacman -Sy ntp --noconfirm 
#clear
#echo ""
#echo ""
#echo "Si toma mucho tiempo en cargar..."
#echo "Presione CONTROL + C para Continuar..."
#echo ""
#ntpd -qg
#sleep 3
#hwclock --systohc
clear


clear && echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando Hora Actual en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
timedatectl status
sleep 5
clear
clear && echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando lista de Keys en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
pacman -Sy archlinux-keyring --noconfirm 
sleep 2
clear

clear && echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando MirrorList en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
#cp pacman.conf /etc/pacman.conf
pacman -Sy reflector python3 rsync --noconfirm 
sleep 2
clear
echo -e "\t\t\t| Actualizando mejores listas de Mirrors |"
echo ""
reflector --verbose --latest 5 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist
sleep 5
clear
cat /etc/pacman.d/mirrorlist
sleep 3
clear
#sed -i '199d' /etc/locale.gen
#sed -i "199i es_ES.UTF-8 UTF-8" /etc/locale.gen

#echo "${locale} UTF-8" > /etc/locale.gen
#locale-gen
#echo LANG=es_ES.UTF-8 > /etc/locale.conf
#export LANG=es_ES.UTF-8
#echo ""
#sleep 2

###########################################
############## CHROOT  ####################
###########################################

nombre_usuario=$user


XORG=$"xorg xorg-apps xorg-xinit xorg-twm xterm xf86-input-libinput"




###########################################
####### FUNCION DE BARRA ##################
###########################################

function barra_progreso {

clear    
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "_"
echo -e ""
echo -e "\t\t\t\t$titulo_progreso"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""

#INICIO PROGRESS BARR
function ProgressBar {
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*6)/10
    let _left=60-$_done
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")
# 1.2.1.1 Progreso : [########################################] 100%
printf "\r > Cargando : |${_fill// /▇}${_empty// /-}| ${_progress}%%"

}
# Variables
_start=1

_end=100

for number in $(seq ${_start} ${_end})
do
    sleep 0.065
    ProgressBar ${number} ${_end}
done
#FIN PROGRESS BARR
echo ""
echo ""
}


function mensaje_install {
echo ""
echo ""
echo -e '\033[38;2;255;0;02m'
echo " █████╗ ██████╗  ██████╗██████╗ ██╗███████╗";
echo "██╔══██╗██╔══██╗██╔════╝██╔══██╗██║██╔════╝";
echo "███████║██████╔╝██║     ██████╔╝██║███████╗";
echo "██╔══██║██╔══██╗██║     ██╔══██╗██║╚════██║";
echo "██║  ██║██║  ██║╚██████╗██║  ██║██║███████║";
echo "╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚══════╝";
echo "                                           ";
echo -e '\033[m'
echo ""
echo ""
sleep 3
}


## FUNCIONES PARA WIFI Y DEMAS COSAS 

microdriver (){

microcode=$(lspci -k | grep 'Host bridge: Intel')
lspci -k | grep 'Host bridge:'  > procesador
if [[ $microcode  = *Intel* || $microcode = *intel* || $microcode = *INTEL* ]]
then
clear    
echo ""
echo ""     
cat procesador
echo ""   
arch-chroot /mnt /bin/bash -c "pacman -S intel-ucode --noconfirm"

else
clear
echo ""
echo ""     
cat procesador
echo ""  
arch-chroot /mnt /bin/bash -c "pacman -S amd-ucode --noconfirm"
fi

}

wifidriver (){

broadcom=$(/bin/bash -c "lspci -k | grep 'Network controller: Broadcom' ")
if [[ $broadcom  = *Broadcom* || $broadcom = *broadcom* || $broadcom = *BROADCOM* ]]
then            
arch-chroot /mnt /bin/bash -c "pacman -S broadcom-wl wireless-regdb wpa_supplicant wireless_tools --noconfirm"
arch-chroot /mnt /bin/bash -c 'modprobe wl' 
arch-chroot /mnt /bin/bash -c 'rmmod b43'
arch-chroot /mnt /bin/bash -c 'rmmod ssb' 
echo Listo
else  
arch-chroot /mnt /bin/bash -c "pacman -S iw wireless_tools wpa_supplicant dialog wireless-regdb --noconfirm"
fi

}

wifidriverdmks (){

broadcom=$(arch-chroot /mnt /bin/bash -c "lspci -k | grep 'Network controller: Broadcom' ")
if [[ $broadcom  = *Broadcom* || $broadcom = *broadcom* || $broadcom = *BROADCOM* ]]
then      
arch-chroot /mnt /bin/bash -c "pacman -S broadcom-wl-dkms wireless-regdb wpa_supplicant wireless_tools --noconfirm"
arch-chroot /mnt /bin/bash -c 'modprobe wl' 
arch-chroot /mnt /bin/bash -c 'rmmod b43' 
arch-chroot /mnt /bin/bash -c 'rmmod ssb' 
echo listo
else
arch-chroot /mnt /bin/bash -c "pacman -S iw wireless_tools wpa_supplicant dialog wireless-regdb --noconfirm"
fi

}

touchdriver () {
arch-chroot /mnt /bin/bash -c "pacman -S xf86-input-synaptics xf86-input-libinput xorg-xinput --noconfirm"
}

blutudriver () {
arch-chroot /mnt /bin/bash -c "pacman -S bluez bluez-utils pulseaudio-bluetooth --noconfirm"
arch-chroot /mnt /bin/bash -c "systemctl enable bluetooth.service"
}

## FINAL FUNCIONES PARA WIFI Y DEMAS COSAS 


###########################################
####### EJECUCION #########################
###########################################

titulo_progreso="| Instalando: Base y Base-devel |"
barra_progreso

pacstrap /mnt base base-devel reflector python3 rsync nano xdg-user-dirs
clear
echo -e "\t\t\t| Actualizando mejores listas de Mirrors del sistema instalado |"
arch-chroot /mnt /bin/bash -c "reflector --verbose --latest 6 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
#cp /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
clear
cat /mnt/etc/pacman.d/mirrorlist
sleep 3
clear
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"

#FSTAB
clear && echo "" 
echo -e ""
echo -e "\t\t\t| Archivo FSTAB |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
genfstab -U /mnt > /mnt/etc/fstab
arch-chroot /mnt /bin/bash -c "cat /etc/fstab"
sleep 4

# Usuarios
clear && echo "" 
echo -e ""
echo -e "\t\t\t| Agregando usuario y /root |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo "$hostname" > /mnt/etc/hostname
echo "127.0.1.1 $hostname.localdomain $hostname" > /mnt/etc/hosts
clear
echo "Hostname: $(cat /mnt/etc/hostname)"
echo ""
echo "Hosts: $(cat /mnt/etc/hosts)"
echo ""
#arch-chroot /mnt /bin/sh -c "echo root:$rootpasswd | chpasswd"
arch-chroot /mnt /bin/bash -c "(echo $rootpasswd ; echo $rootpasswd) | passwd root"
arch-chroot /mnt /bin/bash -c "useradd -m -g users -s /bin/bash $user"
arch-chroot /mnt /bin/bash -c "(echo $userpasswd ; echo $userpasswd) | passwd $user"

#arch-chroot /mnt /bin/bash -c "echo $user:$userpasswd | chpasswd"
sed -i "80i $user ALL=(ALL) NOPASSWD: ALL"  /mnt/etc/sudoers
arch-chroot /mnt /bin/bash -c "hwclock -w"
sleep 2
arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"
clear


# Idioma
clear && echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando Idioma del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo "${locale} UTF-8" > /mnt/etc/locale.gen
arch-chroot /mnt /bin/bash -c "locale-gen" 
echo "LANG=$locale" > /mnt/etc/locale.conf && cat /mnt/etc/locale.conf 
echo "KEYMAP=$keymap" > /mnt/etc/vconsole.conf && cat /mnt/etc/vconsole.conf 

arch-chroot /mnt /bin/bash -c "export $(cat /mnt/etc/locale.conf)" 
export $(cat /mnt/etc/locale.conf)
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario export $(cat /etc/locale.conf)"
export $(cat /mnt/etc/locale.conf)
sleep 3


## DIRECTORIOS
clear && echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando lista de Directoros |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "xdg-user-dirs-update"
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario xdg-user-dirs-update"
echo ""
arch-chroot /mnt /bin/bash -c "ls -l /root/"
echo ""
echo ""
arch-chroot /mnt /bin/bash -c "ls -l /home/$nombre_usuario/"
echo ""
sleep 5
clear


#Zona Horaria
if [ "$zonadefaultNo" == "true" ]; then
ln -sf $timezonedir${timezone} /mnt/etc/localtime
    fi

if [ "$zonadefaultYes" == "true" ]; then
ln -sf /usr/share/zoneinfo/$zonahorariaok /mnt/etc/localtime
    fi
clear

clear && echo "" 
echo -e ""
echo -e "\t\t\t| INICIO DE INSTALACIÓN |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3

if [ "$selecLinuxStable" == "true" ]; then
cp pacman.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi yay-bin --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S linux linux-headers linux-firmware mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist cryptsetup lvm2 logrotate nano hddtemp unzip zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq ethtool ndisc6 inetutils wvdial gptfdisk dhcp dhcpcd dhclient ppp netctl networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd net-tools ifplugd dialog neofetch git wget lsb-release accountsservice bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less ntp usb_modeswitch usbutils which mtools exfat-utils --noconfirm --needed"
    fi

if [ "$selec8168" == "true" ]; then
arch-chroot /mnt /bin/bash -c "pacman -S r8168 --noconfirm"
echo blacklist r8169 > /mnt/etc/modprobe.d/blacklist.conf
cat /mnt/etc/modprobe.d/blacklist.conf
arch-chroot /mnt /bin/bash -c 'modprobe r8168'
sleep 3
fi

if [ "$selecLinuxHard" == "true" ]; then
cp pacman.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi yay-bin --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S linux-hardened linux-hardened-headers linux-firmware mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist cryptsetup lvm2 logrotate nano hddtemp unzip zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq ethtool ndisc6 inetutils wvdial gptfdisk dhcp dhcpcd dhclient ppp netctl networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd net-tools ifplugd dialog neofetch git wget lsb-release accountsservice bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less ntp usb_modeswitch usbutils which mtools exfat-utils --noconfirm --needed"
    fi

if [ "$selecLinuxLts" == "true" ]; then
cp pacman.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi yay-bin --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S linux-lts linux-lts-headers linux-firmware mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist cryptsetup lvm2 logrotate nano hddtemp unzip zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq ethtool ndisc6 inetutils wvdial gptfdisk dhcp dhcpcd dhclient ppp netctl networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd net-tools ifplugd dialog neofetch git wget lsb-release accountsservice bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less ntp usb_modeswitch usbutils which mtools exfat-utils --noconfirm --needed"
    fi

if [ "$selec8168lts" == "true" ]; then
arch-chroot /mnt /bin/bash -c "pacman -Sy r8168-lts --noconfirm"
echo blacklist r8169 > /mnt/etc/modprobe.d/blacklist.conf
cat /mnt/etc/modprobe.d/blacklist.conf
arch-chroot /mnt /bin/bash -c 'modprobe r8168'
sleep 3
    fi
    

if [ "$selecLinuxZen" == "true" ]; then
cp pacman.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi yay-bin --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S linux-zen linux-zen-headers linux-firmware mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist cryptsetup lvm2 logrotate nano hddtemp unzip zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq ethtool ndisc6 inetutils wvdial gptfdisk dhcp dhcpcd dhclient ppp netctl networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd net-tools ifplugd dialog neofetch git wget lsb-release accountsservice bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less ntp usb_modeswitch usbutils which mtools exfat-utils --noconfirm --needed"
    fi

if [ "$microdriverS" == "true" ]; then
microdriver
sleep 3
fi

if [ "$wifidriverS" == "true" ]; then
wifidriver
sleep 3
fi

if [ "$wifidriverdmksS" == "true" ]; then
wifidriverdmks
sleep 3
fi

if [ "$touchdriverS" == "true" ]; then
touchdriver
sleep 3
fi

if [ "$blutudriverS" == "true" ]; then
blutudriver
sleep 3
fi





# REPO_CRISTO FUERA
cp pacman-chroot.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm" 
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm" 

clear


######
#GRUB
######
uefi=$( parted $disk print | grep -ic gpt )

if [ $uefi == 1 ] && [ -d /sys/firmware/efi ]; then
clear
titulo_progreso="| SU SISTEMA ES UEFI |"
barra_progreso
arch-chroot /mnt /bin/bash -c "pacman -S grub efibootmgr os-prober --noconfirm"
clear
echo ""
echo '>>> Su disco es GPT | UEFI es el sistema Moderno <<<'
cat /tmp/partitions | grep gpt 
echo '' 
echo 'Instalando EFI System >> bootx64.efi' 
arch-chroot /mnt /bin/bash -c 'grub-install --target=x86_64-efi --efi-directory=/efi --removable' 
echo '' 
echo 'Instalando UEFI System >> grubx64.efi' 
arch-chroot /mnt /bin/bash -c 'grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=Arch'
######
sed -i "6iGRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"" /mnt/etc/default/grub
sed -i '7d' /mnt/etc/default/grub
######
echo ''
arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
echo '' 
echo 'ls -l /mnt/boot' 
ls -l /mnt/boot 
echo '' 
echo 'Lea bien que no tenga ningún error marcado' 
echo '> Confirme tener las IMG de linux para el arranque' 
echo '> Confirme tener la carpeta de GRUB para el arranque' 
mensaje_install
sleep 3
clear

else
clear
titulo_progreso="|  SISTEMA BIOS LEGACY Y DISCO DOS/MBR  |"
barra_progreso
arch-chroot /mnt /bin/bash -c "pacman -S grub os-prober --noconfirm"
clear
echo "" 
echo '>>> Su disco es DOS MBR | BIOS Legacy es un sistema antiguo <<<' 
echo "" 
cat /tmp/partitions | grep dos 
echo '' 
arch-chroot /mnt /bin/bash -c "grub-install --target=i386-pc $disk"
########
sed -i "6iGRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"" /mnt/etc/default/grub
sed -i '7d' /mnt/etc/default/grub
########
echo '' 
arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
echo '' 
echo 'ls -l /mnt/boot' 
ls -l /mnt/boot 
echo '' 
echo 'Lea bien que no tenga ningún error marcado' 
echo '> Confirme tener las IMG de linux para el arranque' 
echo '> Confirme tener la carpeta de GRUB para el arranque'
mensaje_install
sleep 3
clear
fi
# FIN GRUB





#echo ""
#echo ""
#arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm" 
echo ""
echo ""
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario alsi -l"
#arch-chroot /mnt /bin/bash -c "alsi -l"
echo ""
echo ""
#arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario inxi -Gx"
#arch-chroot /mnt /bin/bash -c "inxi -Gx"
echo ""
echo ""
sleep 5







clear
echo -e "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
echo ""
echo -e '\033[38;2;255;0;02m'
echo " █████╗ ██████╗  ██████╗██████╗ ██╗███████╗";
echo "██╔══██╗██╔══██╗██╔════╝██╔══██╗██║██╔════╝";
echo "███████║██████╔╝██║     ██████╔╝██║███████╗";
echo "██╔══██║██╔══██╗██║     ██╔══██╗██║╚════██║";
echo "██║  ██║██║  ██║╚██████╗██║  ██║██║███████║";
echo "╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚══════╝";
echo "                                           ";
echo -e '\033[m'
echo ""
echo ""
sleep 2
clear

# REPO_CRISTO FUERA
cp pacman-chroot.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm" 
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -Syu --noeditmenu --noconfirm"



if [ "$seleccionDE" == "true" ]; then

titulo_progreso="Instalando Xorg"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $XORG --noeditmenu --noconfirm --needed"
mensaje_install
clear
titulo_progreso="Instalando DE/WM/DM"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $DE --noeditmenu --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $DM --noeditmenu --noconfirm --needed"
clear
echo -e ""
echo -e "\t\t\t\tActivando Servicio Display Manager"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "systemctl enable $(cat DMservice)"
mensaje_install

fi

if [ "$seleccionWM" == "true" ]; then

titulo_progreso="Instalando Xorg"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $XORG --noeditmenu --noconfirm --needed"
mensaje_install
clear
titulo_progreso="Instalando DE/WM/DM"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $WM --noeditmenu --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $DM --noeditmenu --noconfirm --needed"
clear
echo -e ""
echo -e "\t\t\t\tActivando Servicio Display Manager"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "systemctl enable $(cat DMservice)"
mensaje_install

fi



if [ "$seleccionXORG" == "true" ]; then

titulo_progreso="Instalando Xorg"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $XORG --noeditmenu --noconfirm --needed"
mensaje_install


fi


titulo_progreso="Instalando Driver de Vídeo"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $GPU --noeditmenu --noconfirm --needed"
if [ "$VMbox" == "true" ]; then
kernel=$(arch-chroot /mnt uname -a | tail -c -6)
if [ "$kernel" == "Linux" ]; then
    arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S virtualbox-guest-utils xf86-video-vmware virtualbox-host-modules-arch mesa mesa-libgl --noeditmenu --noconfirm --needed"
    GPUvirt="vboxservice"
    echo $GPUvirt | awk -F " " '{print $1}' > GPUvirt                            
else
    arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S virtualbox-guest-dkms virtualbox-host-dkms mesa mesa-libgl --noeditmenu --noconfirm --needed"
    GPUvirt="systemd-modules-load"
    echo $GPUvirt | awk -F " " '{print $1}' > GPUvirt
fi
fi
mensaje_install



if [ "$lirisesion" == "true" ]; then

arch-chroot /mnt /bin/bash -c "systemctl --user enable liri.service"
arch-chroot /mnt /bin/bash -c "systemctl enable liri.service"
arch-chroot /mnt /bin/bash -c "systemctl --user isolate liri.target"

fi



if [ "$programasextrasNO" == "true" ]; then
  clear
  mensaje_install
fi


if [ "$programasextrasSI" == "true" ]; then

if [ "$TERMINAL_condicion" == "true" ]; then
titulo_progreso="Instalando Terminal Seleccionada"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $TERMI --noeditmenu --noconfirm --needed"
mensaje_install
    fi


titulo_progreso="Instalando Utilidades del Sistema"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $UTIL --noeditmenu --noconfirm --needed"
mensaje_install


titulo_progreso="Instalando Sistema de Audio"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $AUDIO --noeditmenu --noconfirm --needed"
mensaje_install 


titulo_progreso="Instalando Tipografias"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S gnome-font-viewer ttf-opensans ttf-hack ttf-font-awesome awesome-terminal-fonts noto-fonts noto-fonts-emoji nerd-fonts-hack ttf-liberation ttf-liberation gnu-free-fonts --noeditmenu --noconfirm --needed"
# ttf-dejavu ttf-bitstream-vera ttf-droid ttf-croscore ttf-ibm-plex 

mensaje_install
#adobe-source-han-sans-jp-fonts
#adobe-source-han-sans-cn-fonts




if [ "$tor_condicion" == "true" ]; then
clear
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "_"
echo -e ""
echo -e "\t\t\t         Actualizando Keys para Tor browser          "
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "gpg --recv-keys EF6E286DDA85EA2A4BA7DE684E2C6E8793298290"
clear
    fi


if [ "$WEB_condicion" == "true" ]; then
titulo_progreso="Instalando navegador Web"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $WEB --noeditmenu --noconfirm --needed"
mensaje_install
    fi


if [ "$spotify_condicion" == "true" ]; then
clear
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' "_"
echo -e ""
echo -e "\t\t\t         Actualizando Keys de Spotify          "
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "gpg --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90"
arch-chroot /mnt /bin/bash -c "gpg --recv-keys 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45"
clear
    fi


if [ "$REPRO_condicion" == "true" ]; then
titulo_progreso="Instalando Reproductor de Música/Vídeo"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $REPRO --noeditmenu --noconfirm --needed"
mensaje_install
    fi



if [ "$OFFICE_condicion" == "true" ]; then
titulo_progreso="Instalando Ofimatica"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $OFFICE --noeditmenu --noconfirm --needed"
mensaje_install
    fi


if [ "$AP_condicion" == "true" ]; then
titulo_progreso="Instalando Administrador de Procesos"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $AP --noeditmenu --noconfirm --needed"
mensaje_install
    fi


if [ "$RS_condicion" == "true" ]; then
titulo_progreso="Instalando Social Media"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $RS --noeditmenu --noconfirm --needed"
mensaje_install
    fi


if [ "$AUR_condicion" == "true" ]; then
titulo_progreso="Instalando AUR Helper"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $AUR --noeditmenu --noconfirm --needed"
mensaje_install
    fi


if [ "$AUR_pamac" == "true" ]; then
clear
echo ""
echo "###############################################################################"
echo "###                  Author    :   Erik Dubois                             ####"
echo "###                  Ver Iconos en Pamac                                   ####"
echo "###############################################################################"
sleep 2
# https://aur.archlinux.org/packages/pamac-aur/
echo "Fix to show icons and applications in pamac-aur"
echo "Downgrading is another solution - see forum for that one"

arch-chroot /mnt /bin/bash -c "zcat /usr/share/app-info/xmls/community.xml.gz | sed 's|<em>||g;s|<\/em>||g;' | gzip > '/tmp/new.xml.gz'"
arch-chroot /mnt /bin/bash -c "cp /tmp/new.xml.gz /usr/share/app-info/xmls/community.xml.gz"
arch-chroot /mnt /bin/bash -c "pacman -S appstream --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "appstreamcli refresh-cache --force"
clear
#arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S pamac-zsh-completions --noeditmenu --noconfirm --needed"
#arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S pamac-tray-icon-plasma --noeditmenu --noconfirm --needed"
#arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S archlinux-appstream-data-pamac --noeditmenu --noconfirm --needed"
#yay -S archlinux-appstream-data-pamac --noeditmenu --noconfirm --needed

mensaje_install
sleep 8
    fi

#FIN DE PROGRAMAS SI EXTRAS
fi



#    AUR_condicion=true
# mkdir /home/$nombre_usuario/.config/  

if [ "$GPUHYBR" == "true" ]; then
arch-chroot /mnt /bin/bash -c "systemctl enable optimus-manager.service"
arch-chroot /mnt /bin/bash -c "optimus-manager --switch auto"
arch-chroot /mnt /bin/bash -c "optimus-manager --set-startup intel"
    fi
    

if [ "$VMbox" == "true" ]; then
arch-chroot /mnt /bin/bash -c "modprobe -a vboxguest vboxsf vboxvideo vboxdrv"
arch-chroot /mnt /bin/bash -c "VBoxClient-all"
arch-chroot /mnt /bin/bash -c "systemctl enable $(cat GPUvirt)"
    fi

    
if [ "$VMqemu" == "true" ]; then
arch-chroot /mnt /bin/bash -c "systemctl enable $(cat GPUvirt)"
    fi



# TEMAS

if [ "$xfce4tema" == "true" ]; then
#TITULO EN BARRAS
titulo_progreso="Instalando Tema de XFCE4"
barra_progreso
#
arch-chroot /mnt /bin/bash -c "mkdir /home/$nombre_usuario/.config"
#
arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/config/master/xfce4.zip"
arch-chroot /mnt /bin/bash -c "unzip xfce4.zip"
arch-chroot /mnt /bin/bash -c "cp -rf xfce4/config/* /home/$nombre_usuario/.config/"
#
arch-chroot /mnt /bin/bash -c "cp -rf xfce4/config/fondo-arch.png /usr/share/backgrounds/xfce/xfce-stripes.png"
arch-chroot /mnt /bin/bash -c "cp -rf xfce4/config/5336864_orig.png /usr/usb.png"
arch-chroot /mnt /bin/bash -c "cp -rf xfce4/config/logo2.png /usr/logo-arch.png"
arch-chroot /mnt /bin/bash -c "cp -rf xfce4/config/logo2.png /home/$nombre_usuario/.face"
arch-chroot /mnt /bin/bash -c "cp -rf xfce4/config/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf"
#
arch-chroot /mnt /bin/bash -c "rm -R xfce4/"
arch-chroot /mnt /bin/bash -c "rm -R xfce4.zip"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/"
sleep 5
    fi


if [ "$i3tema1" == "true" ]; then
#TITULO EN BARRAS
titulo_progreso="Instalando Tema de i3WM"
barra_progreso

arch-chroot /mnt /bin/bash -c "mkdir /home/$nombre_usuario/.config"

arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/config/master/i3-1.zip"
arch-chroot /mnt /bin/bash -c "unzip i3-1.zip"
arch-chroot /mnt /bin/bash -c "cp -rf i3-1/config/* /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "rm -R i3-1/"
arch-chroot /mnt /bin/bash -c "rm -R i3-1.zip"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/"
sleep 5
    fi

if [ "$i3tema2" == "true" ]; then
#TITULO EN BARRAS
titulo_progreso="Instalando Tema de i3WM"
barra_progreso

arch-chroot /mnt /bin/bash -c "mkdir /home/$nombre_usuario/.config"

arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/config/master/i3-2.zip"
arch-chroot /mnt /bin/bash -c "unzip i3-2.zip"
arch-chroot /mnt /bin/bash -c "cp -rf i3-2/config/* /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "rm -R i3-2/"
arch-chroot /mnt /bin/bash -c "rm -R i3-2.zip"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/"
sleep 5
    fi

 

if [ "$plasmatema" == "true" ]; then
#TITULO EN BARRAS
titulo_progreso="Instalando Tema de KDE Plasma"
barra_progreso

arch-chroot /mnt /bin/bash -c "mkdir /home/$nombre_usuario/.config"
arch-chroot /mnt /bin/bash -c "mkdir /home/$nombre_usuario/.local"
arch-chroot /mnt /bin/bash -c "mkdir /home/$nombre_usuario/.kde4"

arch-chroot /mnt /bin/bash -c "wget https://raw.githubusercontent.com/CodigoCristo/config/master/kde.zip"
arch-chroot /mnt /bin/bash -c "unzip kde.zip"
arch-chroot /mnt /bin/bash -c "cp -rf kde/config/* /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "cp -rf kde/local/* /home/$nombre_usuario/.local/"
arch-chroot /mnt /bin/bash -c "cp -rf kde/kde4/* /home/$nombre_usuario/.kde4/"
arch-chroot /mnt /bin/bash -c "rm -R kde/"
arch-chroot /mnt /bin/bash -c "rm -R kde.zip"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.local/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.kde4/"
sleep 3
    fi



if [ "$qtile_config" == "true" ]; then
#TITULO EN BARRAS
titulo_progreso="Configurando Qtile"
barra_progreso

arch-chroot /mnt /bin/bash -c "mkdir -p /home/$nombre_usuario/.config/qtile/"
arch-chroot /mnt /bin/bash -c "cp /usr/share/doc/qtile/default_config.py /home/$nombre_usuario/.config/qtile/config.py"
arch-chroot /mnt /bin/bash -c "python2 -m py_compile /home/$nombre_usuario/.config/qtile/config.py"
echo -e ""
echo -e ""
echo -e "\t> Copiando archivo /.config/qtile/config.py"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3
echo -e ""
echo -e "\t> Ejecutando: python2 -m py_compile /.config/qtile/config.py"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3

arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "chmod 777 $nombre_usuario:users /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/qtile/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/qtile/config.py"
sleep 5
    fi


    if [ "$awesome_config" == "true" ]; then
#TITULO EN BARRAS
titulo_progreso="Configurando Awesome"
barra_progreso

arch-chroot /mnt /bin/bash -c "mkdir -p /home/$nombre_usuario/.config/awesome/"
arch-chroot /mnt /bin/bash -c "cp /etc/xdg/awesome/rc.lua /home/$nombre_usuario/.config/awesome/"

arch-chroot /mnt /bin/bash -c "chmod 777 $nombre_usuario:users /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "chmod 777 $nombre_usuario:users /home/$nombre_usuario/.config/awesome/rc.lua"
    fi

           

#TEMA BSPWM
if [ "$bspwmtema" == "true" ]; then

clear
#TITULO EN BARRAS
titulo_progreso="Configurando BSPWM"
barra_progreso
arch-chroot /mnt /bin/bash -c "git clone https://github.com/darch7/bspwmbydarch-Arcris.git"
arch-chroot /mnt /bin/bash -c "pacman -Rns i3-wm --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy pacman-contrib --noconfirm"

arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/config/*     /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/.local       /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/home/.*      /home/$nombre_usuario/" 
arch-chroot /mnt /bin/bash -c "chmod +x /home/$nombre_usuario/.local/bin/scripts"

arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.config/"
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.local/"


arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/root/fzf/*           /usr/share/fzf"
arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/root/gtk/iconos/*    /usr/share/icons"
arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/root/gtk/temas/*     /usr/share/themes"
arch-chroot /mnt /bin/bash -c "cp -R bspwmbydarch-Arcris/root/wall/*          /usr/share/"

arch-chroot /mnt /bin/bash -c "rm -R /home/$nombre_usuario/compilar" 
arch-chroot /mnt /bin/bash -c "rm -R /home/$nombre_usuario/config" 
arch-chroot /mnt /bin/bash -c "rm -R /home/$nombre_usuario/root" 
arch-chroot /mnt /bin/bash -c "rm /home/$nombre_usuario/README.md" 

sleep 5

fi





if [ "$gnomebeta" == "true" ]; then

titulo_progreso="Instalando Gnome 40"
barra_progreso

arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S chaotic-mirrorlist chaotic-keyring --noeditmenu --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S chaotic-keyring --noeditmenu --noconfirm --needed"
cp pacmanchao.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Sy --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy --noconfirm"

# [chaotic-aur]
# Include = /etc/pacman.d/chaotic-mirrorlist


arch-chroot /mnt /bin/bash -c "pacman -S gnome-control-center --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S gnome-tweaks --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S gnome-terminal --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S gdm --noconfirm"

arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

arch-chroot /mnt /bin/bash -c "pacman -S mutter-40alfa"
arch-chroot /mnt /bin/bash -c "pacman -S gnome-shell-40alfa"
arch-chroot /mnt /bin/bash -c "pacman -S libgweather-git"

arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -R chaotic-mirrorlist chaotic-keyring --noconfirm"
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -R chaotic-keyring --noconfirm"

cp pacman-chroot.conf /mnt/etc/pacman.conf

arch-chroot /mnt /bin/bash -c "pacman -Sy --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy --noconfirm"

#arch-chroot /mnt /bin/bash -c "pacman -S chrome-gnome-shell --noconfirm"


mensaje_install
    fi


















if [ "$aurherlp" == "true" ]; then
titulo_progreso="Eliminando AUR Helper"
barra_progreso
arch-chroot /mnt /bin/bash -c "pacman -R $AUR_DELETE --noconfirm"
mensaje_install
    fi


# Ejemplo 
# variable=false
# variable=true
# if [ "$variable" == "true" ]; then
#    echo contenido_a_mostrar
#    fi

clear


titulo_progreso="Instalando Shell del Sistema"
barra_progreso
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario yay -S $SH --noeditmenu --noconfirm --needed"
mensaje_install
clear



echo ''
echo ''


echo $SH | awk -F " " '{print $1}' >> shell
SH=$(cat shell)
arch-chroot /mnt /bin/bash -c "chsh -s /bin/$SH"
arch-chroot /mnt /bin/bash -c "chsh -s /usr/bin/$SH $nombre_usuario"
arch-chroot /mnt /bin/bash -c "chsh -s /bin/$SH $nombre_usuario"
#arch-chroot /mnt /bin/bash -c "cp /root/bashrc /root/.bashrc"


cp .dialogrc /mnt/root
chmod +x /mnt/root/.dialogrc
cp .dialogrc /mnt/home/$nombre_usuario/.dialogrc
chmod +x /mnt/home/$nombre_usuario/.dialogrc

mkdir /mnt/etc/pacman.d/hooks/
cp mirrorupgrade.hook /mnt/etc/pacman.d/hooks/mirrorupgrade.hook 
chmod +x /mnt/etc/pacman.d/hooks/mirrorupgrade.hook

cp zshrc /mnt/home/$nombre_usuario/.zshrc
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.zshrc"
cp zshrc /mnt/root/.zshrc

cp .bashrc /mnt/home/$nombre_usuario/.bashrc
cp .bashrc-root /mnt/root/.bashrc
arch-chroot /mnt /bin/bash -c "chown -hR $nombre_usuario:users /home/$nombre_usuario/.bashrc"



rm shell
rm DMservice
rm GPUvirt
clear


arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "ls -l /home/$nombre_usuario"
echo ''
echo ''


####################################################################
clear
arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"
clear
arch-chroot /mnt /bin/bash -c "systemctl start dhcpcd NetworkManager"
clear
echo "noipv6rs" >> /mnt/etc/dhcpcd.conf
echo "noipv6" >> /mnt/etc/dhcpcd.conf

sed -i '80d' /mnt/etc/sudoers
sed -i "80i $nombre_usuario ALL=(ALL) ALL" /mnt/etc/sudoers
clear
####################################################################



#arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario localectl set-x11-keymap $keymap"
#sleep 3
clear
#Load the X11 keymap
cmd=(dialog --backtitle "Canal de Youtube: Codigo Cristo" --title "-| Definir teclado para X.org |-" --keep-tite --menu "\n" 10 0 10)

options=(latam      ""
         es         ""
         us         ""
         otros      "(+)")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        es) 
            clear
            keyboard="es"
            keymap="es"
            arch-chroot /mnt /bin/bash -c "localectl --no-convert set-x11-keymap es"
      arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario localectl --no-convert set-x11-keymap es"
      arch-chroot /mnt /bin/bash -c "setxkbmap -layout es"
      arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario setxkbmap -layout es"
      echo -e 'Section "InputClass"' > /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'Identifier "system-keyboard"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'MatchIsKeyboard "on"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'Option "XkbLayout" "es"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'EndSection' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      cat /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      sleep 5
      clear
            ;;
            
        latam)
            clear
            keyboard="latam"
            keymap="latam"
            arch-chroot /mnt /bin/bash -c "localectl --no-convert set-x11-keymap latam"
      arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario localectl --no-convert set-x11-keymap  latam"
      arch-chroot /mnt /bin/bash -c "setxkbmap -layout latam"
      arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario setxkbmap -layout latam"
      echo -e 'Section "InputClass"' > /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'Identifier "system-keyboard"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'MatchIsKeyboard "on"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'Option "XkbLayout" "latam"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'EndSection' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      cat /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      sleep 5
      clear
            ;;
            
        us)
            clear
            keyboard="us"
            keymap="us"
            arch-chroot /mnt /bin/bash -c "localectl --no-convert set-x11-keymap us"
      arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario localectl --no-convert set-x11-keymap us"
      arch-chroot /mnt /bin/bash -c "setxkbmap -layout us"
      arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario setxkbmap -layout us"
      echo -e 'Section "InputClass"' > /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'Identifier "system-keyboard"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'MatchIsKeyboard "on"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'Option "XkbLayout" "us"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      echo -e 'EndSection' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      cat /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
      sleep 5
      clear
            ;;
            
        otros)
            clear
            selected1=0 
            while [ $selected1 == "0" ];do 
                locales="$(arch-chroot /mnt localectl list-x11-keymap-layouts | awk '$locales=$locales" Keyboard"')" && locales=$(echo "$locales") 
                keyboard=$(dialog --backtitle "Canal de Youtube: Codigo Cristo" --clear --title "-| Teclado en X.org |-" --menu "\n" 15 0 15   ${locales} 2>&1 > /dev/tty) 
                if [ $? == 0 ];then 
                    clear
                    keymap=$keyboard
                    arch-chroot /mnt /bin/bash -c "localectl --no-convert set-x11-keymap $keymap"
          arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario localectl --no-convert set-x11-keymap $keymap"
          arch-chroot /mnt /bin/bash -c "setxkbmap -layout $keymap"
          arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario setxkbmap -layout $keymap"
          echo -e 'Section "InputClass"' > /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
          echo -e 'Identifier "system-keyboard"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
          echo -e 'MatchIsKeyboard "on"' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
          echo -e "Option "XkbLayout" "$keymap"" >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
          echo -e 'EndSection' >> /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
          cat /mnt/etc/X11/xorg.conf.d/00-keyboard.conf
          sleep 5
          clear
                    selected1=1 
                else 
                    dialog --backtitle "Canal de Youtube: Codigo Cristo" --title "-| ERROR |-" --stdout --ok-label 'Siguiente' --msgbox "Ingrese correctamente el teclado para continuar" 5 55 
                fi
            done
            ;;
    esac
done
#FIN the X11 keymap
clear

# MENSAJE FINAL
dialog --backtitle "Canal de Youtube: Codigo Cristo" \
--title "-| CREDITOS |-" --ok-label '- ¡ Gracias Totales ! -' --nocancel \
--column-separator "|" --msgbox "\n                    + Creador: Codigo Cristo +\n \
\n+ Aportaciones de la Comunidad: \n \
\n> Miqueas Martinez | @Miqueas2020 \
\n> Wilsson Martee   | @Bourne_Again \
\n> Alex             | @nahuelwexd \
\n> MXHECTORVEGA     | @mxhectorvega \
\n> Cargando...      | @konrc \
\n> Eduard Tolosa    | @edu4rdt " 16 73

clear



#nombre_usuario=$(cat /mnt/etc/passwd | grep '/home' | cut -d: -f1) 
#sed -i "80i $nombre_usuario ALL=(ALL) NOPASSWD: ALL" /mnt/etc/sudoers


#mensaje_install
#sleep 2
#clear
#echo ''
#arch-chroot /mnt /bin/bash -c "alsi -l"



cp pacman-chroot.conf /mnt/etc/pacman.conf



# cp pacman-chroot.conf /etc/pacman.conf
clear
echo ''
echo ''
arch-chroot /mnt /bin/bash -c "sudo -u $nombre_usuario alsi -l"
echo ''
echo https://t.me/ArchLinuxCristo 
echo ''
echo ''
echo ""
printf "\n| La computadora se reiniciara para finalizar |\n| Cuando este apagada la computadora retire la USB o CD |\n\n"

#INICIO PROGRESS BARR
function ProgressBar {
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*6)/10
    let _left=60-$_done
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")
# 1.2.1.1 Progreso : [########################################] 100%
printf "\r > Cargando : |${_fill// /▇}${_empty// /-}| ${_progress}%%"

}
# Variables
_start=1

_end=100

for number in $(seq ${_start} ${_end})
do
    sleep 0.1
    ProgressBar ${number} ${_end}
done
#FIN PROGRESS BARR

swapdisco=$( fdisk -l | grep "/dev/\|swap" | grep swap | awk -F ' ' '{print $1}' )
umount -R /mnt
swapoff ${swapdisco}
swapoff -a
swapon -a
clear

reboot

else

# MENSAJE 
dialog --backtitle "$titulo" \
--title "-| Error |-" \
--msgbox "\n> No selecciono todas las opciones disponibles \
\n> Esto puede generar errores por falta de información \n \
\n> Vuelva a seleccionar en orden toda la lista que ofrece el Script Arcris <" 10 80

main

fi


;;
## FIN DE INSTALL

"11")
rm -r arcris
clear && echo "" 
echo -e ""
echo -e "\t\t\t| Visita Nuestra Comunidad - https://t.me/ArchLinuxCristo - by: Arcris |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo "" && sleep 3 && exit
;;

    esac
done

}

main