#!/bin/sh
: 'Copyright (C) 2019 Código Cristo'
#!/bin/bash

# @Bourne_Again
# wget is.gd/arcris && sh arcris
# https://is.gd/stats.php?url=arcris

clear

pacman -Sy

pacmaninit=$( pacman -S glibc dialog curl --noconfirm --needed | wc -l )

if [[ "$pacmaninit" = "7" ]] ; then
clear
else
sudo pacman -Sy glibc dialog curl --noconfirm --needed
fi
sleep 3

clear
curl -LJO github.com/CodigoCristo/arcrisnew/archive/refs/heads/main.tar.gz
tar  -xvf  arcrisnew-main.tar.gz
cd arcrisnew-main

cp .dialogrc /root
chmod +x *
sleep 2
clear
sh arcris-install