#!/bin/sh
: 'Copyright (C) 2019 Código Cristo'
#!/bin/bash

# @Bourne_Again
# wget is.gd/arcris && sh arcris
# https://is.gd/stats.php?url=arcris

clear
pacman -Sy --noconfirm
pacman -Sy 
pacman -Sy 
clear

pacmaninit1=$( pacman -Ss glibc  | grep "glibc" 	| grep "installed" | wc -l )
pacmaninit2=$( pacman -Ss dialog | grep "dialog" 	| grep "installed" | wc -l )
pacmaninit3=$( pacman -Ss curl 	 | grep "curl" 		| grep "installed" | wc -l )

if [[ "$pacmaninit1" = "1" && "$pacmaninit2" = "1" && "$pacmaninit3" = "1" ]] ; then
clear
else
clear
sudo pacman -Sy glibc dialog curl --noconfirm --needed
sleep 5
fi

clear
curl -LJO github.com/CodigoCristo/arcrisnew/archive/refs/heads/main.tar.gz
clear
tar  -xvf  arcrisnew-main.tar.gz
cd arcrisnew-main

cp .dialogrc /root
chmod +x *
clear
echo "Loading..."
sleep 1
sh arcris-install