#!/usr/bin/env bash

# git add .  
# git commit -m 'testing'
# git push -f
# curl -L is.gd/arcrisnew > arcris ; sh arcris 

    echo "" 
    welcome_title=" -| Language Select - Selecciona tu Idioma |- "

    LANG=$(dialog --nocancel --backtitle "Welcome : $(date -u "+%F %H:%M")" --title "${welcome_title}" \
    --menu "\nInstallation wizard ArcriS\n\nSelect your install language:" 12 60 10 \
        "English" "English" \
        "Spanish" "Español" 3>&1 1>&2 2>&3)

    case "$LANG" in

        "English") 
        source languages/english.conf
        ;;

        "Spanish") 
        source languages/español.conf
        echo "$LANGUAGE UTF-8" > /etc/locale.gen
        locale=$(locale-gen)
        dialog --backtitle "$titulo" \
        --title "-| Configurando Idioma |-" --stdout --ok-label "Siguiente" \
        --infobox "$locale" 20 150
        echo "LANG=$LANGUAGE" > /etc/locale.conf
        export LANG=$LANGUAGE
        ;;

    esac


dialog --backtitle "$titulo" \
--title "${alerta}" \
--msgbox "${msg}" 13 50