#!/bin/sh
: 'Copyright (C) 2019 Código Cristo'
#!/bin/bash

# @Bourne_Again
# wget is.gd/arcris && sh arcris
# https://is.gd/stats.php?url=arcris

clear

pacmaninit=$( pacman -Sy glibc dialog curl --noconfirm --needed | wc -l )

if [[ "$pacmaninit" = "1" ]] ; then
clear
else
clear
sudo pacman -Sy glibc dialog curl --noconfirm --needed
sleep 5
fi

clear
curl -LJO github.com/CodigoCristo/arcrisnew/archive/refs/heads/main.tar.gz
clear
tar  -xvf  arcrisnew-main.tar.gz
cd arcrisnew-main

cp .dialogrc /root
chmod +x *
clear
sh arcris-install