#!/usr/bin/env bash

# git add .  
# git commit -m 'testing'
# git push -f
# curl -L is.gd/arcrisnew > arcris ; sh arcris 

    echo ""
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
    locale=$(locale-gen)
    dialog --stdout --infobox "$locale" 20 150
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    export LANG=en_US.UTF-8


    welcome_title=" -| Language Select |- "


cmd=(dialog --nocancel --backtitle "Welcome : $(date "+%A, %B %d, %Y - %I:%M %p")" --title "${welcome_title}" \
    --menu "\nDonations in: www.patreon.com/codigocristo\n\nSelect the language of the installer:\n\n---------------------------------------------\n\nDonaciones en: www.patreon.com/codigocristo\n\nSeleccione el idioma del instalador:\n " 20 60 10)

options=(1 "Español"
         2 "English"
         3 "Russian")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1)
        clear
        source languages/español.conf
        echo "$LANGUAGE UTF-8" 
        echo "Hola"
            ;;
        2)
            echo "Second Option"
            ;;
        3)
            echo "Third Option"
            ;;
        4)
            echo "Fourth Option"
            ;;
    esac
done