#!/bin/bash

GRUBINSTALL=1



case $GRUBINSTALL in

  1)
    echo "STATEMENTS 1"
    ;;

  2)
    echo "STATEMENTS"
    ;;

  3)
    echo "STATEMENTS"
    ;;

  *)
    echo "STATEMENTS"
    ;;
esac


