#!/bin/bash

sectionubi=0


if [[ $sectionuser == "0" ]]; then
    dialog --backtitle "${title}" --title "-| ERROR |-" --stdout --msgbox "\n\nNo has creado un usuario correctamente...\n " 8 50    

elif [[ $sectionubi == "0" ]]; then
    dialog --backtitle "${title}" --title "-| ERROR |-" --stdout --msgbox "\n\nTe falta seleccionar su Ubicación.\n " 8 40

else
	echo mal
fi
