#!/bin/bash

disksystem () {

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Discos |-" \
--ok-label "Confirmar" --menu "\nEliga su mejor opción para su Sistema\n " 15 60 15)
options=(1 " Particionado Automático                       "   
         2 " Particionado Automático con Cifrado de Disco  "
         3 " Particionado Manual                           "
         4 " Particionado con otro Sistema Operativo       "
         5 " Cambia o Crea tu Tabla de partición del Disco "
         6 " Formatea todo tu Disco con DD                 ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
    ################

1) ################ 
source lib/partition/autopartition
autopartition
;;

2) ################
shell="bash"
;;
3) ################
source lib/partition/manualpartition
manualpartition
;;

4) ################
shell="dash"
;;


5) ################
source lib/partition/tabledisk
tabledisk
;;


6) ################
source lib/partition/deletediskdd
deletediskdd
;;

    esac
done



}


