#!/bin/bash

disksystem () {

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Disco Duro |-" \
--ok-label "Confirmar" --nocancel --menu "\nEliga su mejor opción para su Sistema\n " 15 57 15)
options=(1 " Particionado Automático                       "   
         2 " Particionado Automático con Cifrado de Disco  "
         3 " Particionado Manual                           "
         4 " Particionado con otro Sistema Operativo       "
         5 " Cambia o Crea tu Tabla de partición del Disco "
         6 " Formatea todo tu Disco con DD                 ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
    ################

1) ################ 
source lib/partition/autopartition
autopartition
;;

2) ################
shell="bash"
;;
3) ################
shell="fish"
;;

4) ################
shell="dash"
;;


5) ################
shell="dash"
;;


6) ################
source lib/partition/deletediskdd
deletediskdd
;;
                                                
    esac
done



}


