#!/bin/bash

environment () {

DE=""
DM=""
WM=""
seleccionDE=false
seleccionWM=false
seleccionXORG=false
seleccionTTY=false



cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --title "-| Entorno |-" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --nocancel --menu "\nElige una opción\n " 12 50 12)

options=(3 "Emulador de Terminal | (tty)"
         1 "Entorno de escritorio | (DE)"
         2 "Gestor de ventanas | (WM)")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1) #INICIO (DE)    

seleccionDE=true

cmd=(dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" --column-separator "|" --no-tags --ok-label '< Seleccionar >' --menu "Selecciona tu escritorio a instalar - (DE)" 22 60 19)

options=(1 " > | xfce4 | Xfce desktop| <"
         2 " > | gnome | GNOME Classic desktop| <")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        
###########SELECCION (DE)
        1) #XFCE4


cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n\
Selecciona una opción para XFCE4 \n " 12 60 20)

options=(1 "   Xfce4                    "
         2 "   Xfce4 - Tema Arcris      ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="Xfce4"
            ;;
            
        2)  DE="Xfce4 Arcris"
            ;;
            
    esac
done
        ;;
        ######FINAL XFCE4

        2)  #INICIO GNOME
cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags \
--ok-label '< Seleccionar >' --nocancel --menu "\n \
Selecciona una opción para GNOME \n " 12 60 20)

options=(1 "   Gnome || Sistema Completo  "
         2 "   Gnome || Minimalista       ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in

        1)  DE="Gnome"
            ;;
            
        2)  DE="Gnome Lite"
            ;;

    esac
done
            ;;
 
    esac
done
            ;;
#########FIN ESCRITORIO


        2) #INICIO (WM)
seleccionWM=true

cmd=(dialog --keep-tite --backtitle "${title}" \
--no-collapse --cr-wrap --column-separator "|" --no-tags --ok-label '< Seleccionar >' --menu "Selecciona tu gestor de ventana a instalar - (WM)" 20 55 16)

options=(1 "> i3wm | 150MB de RAM "
         2 "> qtile | Disponible <"
         3 "> Awesome | Disponible <")


choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        1)  
            WM="i3wm"
            ;;

        2)
            WM="qtile"
            ;;

        3)
            WM="awesome"
            ;;

    esac
done
#FINAL (WM)
            ;;
            

        3)
          seleccionTTY=true
          tty="tty"
          ;;


    esac
done

sectionenv=1

}


