#!/bin/bash

extraprogram () {


extraprograms=true


while [[ $extraprograms == "true" ]]; do

menuextras=$(dialog --keep-tite --backtitle "${title}" --title "-| EXTRAS |-" \
--nocancel --no-tags \
--menu "\nSeleccione los programas extras que necesita \n " 21 50 10 \
1 "           Utilidades                   " \
2 "           Terminales                   " \
3 "           Audio                        " \
4 "           Reproductores                " \
5 "           Navegador Web                " \
6 "           Office                       " \
7 "           Administrador de tareas      " \
8 "           Social media                 " \
9 "           Gamers                       " \
10 "           AUR helpers                  " \
11 " CONFIRMAR  " \
12 " CANCELAR   " 3>&1 1>&2 2>&3)

case "$menuextras" in

"1")

;;

"2") 

;;


"3")

;;

"4") 

;;

"5")


;;

"6")


;;

"7")
#Administrador de Tareas
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Administrador de Tareas |-" \
--no-tags  --checklist "\n[ ESPACIO ] - Para marcar o desmarcar *\n " 15 70 20)
options=(1 " gnome-system-monitor " on
         2 " htop                 " on
         3 " bashtop              " off
         4 " gtop                 " off
         5 " gotop - AUR          " off)

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1)
            AP1="gnome-system-monitor"
            AP_condicion=true
            ;;
        2)
            AP2="htop"
            AP_condicion=true
            ;;
        3)
            AP3="bashtop"
            AP_condicion=true
            ;;
        4)
            AP4="gtop"
            AP_condicion=true
            ;;

        5)
            AP5="gotop"
            AP_condicion=true
            ;;
            
            
    esac
done

;;

"8")


;;

"9")

;;

"10")

;;

"11")

;;

"12")
extraprograms=false
break
;;

    esac
done


}


