#!/bin/bash

install () {


logoline1='                             -`                        '
logoline2='                           .o+`                        '
logoline3='                           `ooo/                       '
logoline4='                          `+oooo:                      '
logoline5='                         `+oooooo:                     ' 
logoline6='                         -+oooooo+:                    '
logoline7='                       `/:-:++oooo+:                   '
logoline8='                      `/++++/+++++++:                  '
logoline9='                     `/++++++++++++++:                 '
logoline11='                    `/+++ooooooooooooo/`               '
logoline12='                   ./ooosssso++osssssso+`              '
logoline13='                  .oossssso-````/ossssss+`             '
logoline14='                 -osssssso.      :ssssssso.            '
logoline15='                :osssssss/        osssso+++.           '
logoline16='               /ossssssss/        +ssssooo/-           '
logoline17='             `/ossssso+/:-        -:/+osssso+-         '
logoline18='            `+sso+:-`                 `.-/+oso:        '
logoline19='           `++:.                           `-/+/       '
logoline20='           .`                                 `/       '
logoline21="                          _                  _         "
logoline22="  .--.                   / \   _ __ ___ _ __(_)___     "
logoline23=" / _.-' .-.  .-.  .-.   / _ \ | '__/ __| '__| / __|    "
logoline24=" \  '-. '-'  '-'  '-'  / ___ \| | | (__| |  | \__ \    "
logoline25="  '--'                /_/   \_\_|  \___|_|  |_|___/    "

red='\033[38;2;255;1;31m'
clear
echo ""
echo ""
echo -e $red


if [[ ${zonemanual} == true ]]; then
    zonahoraria=${$timezone}
else
    zonahoraria=${zoneinfo}
fi


if [[ $seleccionDE == true ]]; then
    environment=$DE
elif [[ $seleccionWM == true ]]; then
    environment=$WM
elif [[ $seleccionXORG == true ]]; then
    environment=$xorg
else
    environment=$tty
fi

setfont default8x16
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo ""
echo "  - Elecciones del usuario :"
echo ""
echo ""
echo -e "${logoline1}"
echo -e "${logoline2}"
echo -e "${logoline3} Kernel  : ${kernel_select}"
echo -e "${logoline4}"
echo -e "${logoline5} Disco   : ${disk}"
echo -e "${logoline6}"
echo -e "${logoline7} Usuario : ${username}"
echo -e "${logoline8}"
echo -e "${logoline9} Idioma  : ${keymap}"
echo -e "${logoline11}"
echo -e "${logoline12} Zona Horaria : ${zonahoraria}"
echo -e "${logoline13}"
echo -e "${logoline14} Ubicación : ${locale}"
echo -e "${logoline15}"
echo -e "${logoline16} Driver de Vídeo : ${video}"
echo -e "${logoline17}"
echo -e "${logoline18} Entorno Gráfico : ${environment}"
echo -e "${logoline19}"
echo -e "${logoline20}"
echo -e "${logoline21}"
echo -e "${logoline22}"
echo -e "${logoline23}"
echo -e "${logoline24}"
echo -e "${logoline25}"
echo ""
echo ""
echo "  Arcris Instalación fácil de ArchLinux - Donaciones en: www.patreon.com/codigocristo"
echo ""
echo ""

function ProgressBar {
    let _progress=(${1}*100/${2}*100)/100
    let _done=(${_progress}*6)/10
    let _left=60-$_done
    _fill=$(printf "%${_done}s")
    _empty=$(printf "%${_left}s")
# 1.2.1.1 Progreso : [########################################] 100%
printf "\r   |${_fill// /▇}${_empty// /-}| ${_progress}%%"

}
# Variables
_start=1

_end=100

for number in $(seq ${_start} ${_end})
do
    sleep 0.1
    ProgressBar ${number} ${_end}
done

echo -e '\033[m'
setfont lat5-16


}




















install2 () {

red='\033[38;2;255;1;31m'
clear
echo ""
echo ""
echo -e $red '                             -`                        '
echo -e $red '                           .o+`                        '
echo -e $red '                           `ooo/                       Kernel  : ${kernel_select}'
echo -e $red '                          `+oooo:                      '
echo -e $red '                         `+oooooo:                     Disco   : ' 
echo -e $red '                         -+oooooo+:                    '
echo -e $red '                       `/:-:++oooo+:                   Usuario : '
echo -e $red '                      `/++++/+++++++:                  '
echo -e $red '                     `/++++++++++++++:                 Idioma  : '
echo -e $red '                    `/+++ooooooooooooo/`               '
echo -e $red '                   ./ooosssso++osssssso+`              Zona Horaria :'
echo -e $red '                  .oossssso-````/ossssss+`             '
echo -e $red '                 -osssssso.      :ssssssso.            Ubicación :'
echo -e $red '                :osssssss/        osssso+++.           '
echo -e $red '               /ossssssss/        +ssssooo/-           Driver de Vídeo : '
echo -e $red '             `/ossssso+/:-        -:/+osssso+-         '
echo -e $red '            `+sso+:-`                 `.-/+oso:        Entorno Gráfico : '
echo -e $red '           `++:.                           `-/+/       '
echo -e $red '           .`                                 `/       '
echo -e $red "                          _                  _         "
echo -e $red "  .--.                   / \   _ __ ___ _ __(_)___     "
echo -e $red " / _.-' .-.  .-.  .-.   / _ \ | '__/ __| '__| / __|    "
echo -e $red " \  '-. '-'  '-'  '-'  / ___ \| | | (__| |  | \__ \    "
echo -e $red "  '--'                /_/   \_\_|  \___|_|  |_|___/    "

echo -e '\033[m'

read line

}
