#!/bin/bash

install () {

red='\033[38;2;255;1;31m'
clear
echo ""
echo ""
echo ""
echo -e $red '                             -`                  '
echo -e $red '                           .o+`                  '
echo -e $red '                           `ooo/                   '
echo -e $red '                          `+oooo:                 '
echo -e $red '                         `+oooooo:                 ' 
echo -e $red '                         -+oooooo+:                '
echo -e $red '                       `/:-:++oooo+:              '
echo -e $red '                      `/++++/+++++++:              '
echo -e $red '                     `/++++++++++++++:             '
echo -e $red '                    `/+++ooooooooooooo/`           '
echo -e $red '                   ./ooosssso++osssssso+`          '
echo -e $red '                  .oossssso-````/ossssss+`         '
echo -e $red '                 -osssssso.      :ssssssso.        '
echo -e $red '                :osssssss/        osssso+++.       '
echo -e $red '               /ossssssss/        +ssssooo/-       '
echo -e $red '             `/ossssso+/:-        -:/+osssso+-     '
echo -e $red '            `+sso+:-`                 `.-/+oso:    '
echo -e $red '           `++:.                           `-/+/   '
echo -e $red '           .`                                 `/   '
echo ""
echo -e $red "            Visita el Canal de Youtube de Código Cristo"
echo -e '\033[m'



}


