#!/bin/bash

kerneles () {

### KERNEL 
selecLinuxStable=false
selecLinuxHard=false
selecLinuxLts=false
selecLinuxZen=false

microdriverS=false
wifidriverS=false
wifidriverdmksS=false
touchdriverS=false
blutudriverS=false

selec8168=false
selec8168lts=false

kernel_var=0 



while [ "$kernel_var" = "0" ] ; do

kernel_select=$(dialog --backtitle "${title}" --title "-| KERNEL |-" \
--stdout --ok-label "Selecciona" --no-cancel --menu "\nElige que kernel necesitas: \n\n\
> Linux Stable es la mejor opción\n\nLas otras opciones tienen un estilo diferente para \
instalar Drivers\nLas otras modificaciones del kernel trabajan con Drivers Libres\n " 18 0 200 \
"linux-stable"  " Kernel en su versión estable y módulos de Vanilla Linux " \
"linux-hardened"  " Kernel enfocado en Seguridad                            " \
"linux-lts"  " Kernel con soporte de larga duración                    " \
"linux-zen"  " Kernel del esfuerzo colaborativo de varios hackers      ")

#####Stable  
  if [ $kernel_select == linux-stable ]; then
##################################################################################
    r8168=$(arch-chroot /mnt /bin/bash -c "lspci -k | grep 'RTL8111/8168/8411' ")
    if [[ $r8168  = *RTL8111/8168/8411* || $r8168 = *Rtl8111/8168/8411* || $r8168 = *rtl8111/8168/8411* ]]
    then      
    selec8168=true
    install8169=r8168
    fi

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --title "-| Extras Kernel |-" --checklist "Selecciona los modulos que necesitas\n[ ESPACIO ] - Para marcar o desmarcar *" 12 70 10)
options=(1 " Actualizaciones del Microcode  " on    # any option can be set to default to "on"
         2 " Módulo para Wi-fi              " off
         3 " Módulo para Touchpad (Laptops) " off
         4 " Módulo para Bluetooth          " off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) microdriverS=true
        ;; 
        2) wifidriverS=true
        ;; 
        3) touchdriverS=true
        ;;
        4) blutudriverS=true
        ;;
    esac
done

  selecLinuxStable=true
  kernel_var=1


#####hardened
  elif [ $kernel_select == linux-hardened ]; then

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --title "-| Extras Kernel |-" --checklist "Selecciona los modulos que necesitas\n[ ESPACIO ] - Para marcar o desmarcar *" 12 70 10)
options=(1 " Actualizaciones del Microcode  " on    # any option can be set to default to "on"
         2 " Módulo para Wi-fi              " off
         3 " Módulo para Touchpad (Laptops) " off
         4 " Módulo para Bluetooth          " off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) microdriverS=true
        ;; 
        2) wifidriverdmksS=true
        ;; 
        3) touchdriverS=true
        ;;
        4) blutudriverS=true
        ;;
    esac
done

  selecLinuxHard=true
  kernel_var=1



######LTS
  elif [ $kernel_select == linux-lts ]; then
##################################################################################
    r8168=$(arch-chroot /mnt /bin/bash -c "lspci -k | grep 'RTL8111/8168/8411' ")
    if [[ $r8168  = *RTL8111/8168/8411* || $r8168 = *Rtl8111/8168/8411* || $r8168 = *rtl8111/8168/8411* ]]
    then      
    selec8168lts=true
    install8169=r8168-lts
    fi
cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --title "-| Extras Kernel |-" --checklist "Selecciona los modulos que necesitas\n[ ESPACIO ] - Para marcar o desmarcar *" 12 70 10)
options=(1 " Actualizaciones del Microcode  " on    # any option can be set to default to "on"
         2 " Módulo para Wi-fi              " off
         3 " Módulo para Touchpad (Laptops) " off
         4 " Módulo para Bluetooth          " off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) microdriverS=true
        ;; 
        2) wifidriverdmksS=true
        ;; 
        3) touchdriverS=true
        ;;
        4) blutudriverS=true
        ;;
    esac
done
  
  selecLinuxLts=true
  kernel_var=1  


###### ZEN
  elif [ $kernel_select == linux-zen ]; then
##################################################################################

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --separate-output --column-separator "|" \
--no-tags --ok-label '< Siguiente >' --cancel-label '< No deseo esto >' --title "-| Extras Kernel |-" --checklist "Selecciona los modulos que necesitas\n[ ESPACIO ] - Para marcar o desmarcar *" 12 70 10)
options=(1 " Actualizaciones del Microcode  " on    # any option can be set to default to "on"
         2 " Módulo para Wi-fi              " off
         3 " Módulo para Touchpad (Laptops) " off
         4 " Módulo para Bluetooth          " off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
        1) microdriverS=true
        ;; 
        2) wifidriverdmksS=true
        ;; 
        3) touchdriverS=true
        ;;
        4) blutudriverS=true
        ;;
    esac
done
   
  selecLinuxZen=true
  kernel_var=1
  
  
  fi
done


}


