#!/bin/bash

cmd=(dialog --backtitle "$titulo" --title "-| Listado de teclado en TTY |-" --no-cancel --keep-tite --menu "\nComando ejecutado:\nlocalectl list-keymaps \n " 15 50 11)

options=(la-latin1  "Latino Americano"
         es     	  "Español"
         us     	  "Ingles"
         ru			    "Ruso"
         otros      "(+)Teclados")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        es)
            loadkeys es
      keyboard="es"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;
            
        la-latin1)
            loadkeys la-latin1
      keyboard="la-latin1"
      loadkeys=$keyboard 
      keymap=$keyboard 
            ;;
            
        us)
            loadkeys us
      keyboard="us"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;
            
        otros)
            selected=0 
      while [ $selected == "0" ];do 
        localeskeymap="$(localectl list-keymaps | awk '$localeskeymap=$localeskeymap" Keyboard"')" && localeskeymap=$(echo "$localeskeymap") 
        keyboard=$(dialog --backtitle "$titulo" --clear --no-cancel --title "-| Distribución del teclado: |-" --menu " \n " 15 50 15   ${localeskeymap} 2>&1 > /dev/tty) 
        if [ $? == 0 ];then 
          loadkeys $keyboard 
          keymap=$keyboard 
          selected=1 
        else 
          dialog --backtitle "$titulo" --title "-| ERROR |-" --stdout --ok-label 'Siguiente' --msgbox "Ingrese una distribución del teclado para continuar" 5 55 
        fi
      done
        ;;
    esac
done



###########################################


cmd=(dialog --backtitle "$titulo" --title "-| Listado de teclado en X.org |-" --no-cancel --keep-tite --menu "\nComando ejecutado:\nlocalectl list-x11-keymap-layouts\n " 15 50 11)

options=(latam  	"Latino Americano"
         es     	"Español"
         us     	"Ingles"
         ru			  "Ruso"
         otros    "(+)Teclados")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in
        es)
            loadkeys es
      keyboard="es"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;
            
        la-latin1)
            loadkeys la-latin1
      keyboard="la-latin1"
      loadkeys=$keyboard 
      keymap=$keyboard 
            ;;
            
        us)
            loadkeys us
      keyboard="us"
      loadkeys=$keyboard 
      keymap=$keyboard  
            ;;
            
        otros)
            selected=0 
      while [ $selected == "0" ];do 
        localeskeymapx="$(cat lib/list_X11keymap | awk '$localeskeymapx=$localeskeymapx" Keyboard"')" && localeskeymapx=$(echo "$localeskeymapx") 
        keyboard=$(dialog --backtitle "$titulo" --clear --no-cancel --title "-| Distribución del teclado en X.org |-" --menu " \n " 15 50 15   ${localeskeymapx} 2>&1 > /dev/tty) 
        if [ $? == 0 ];then 
          loadkeys $keyboard 
          keymapx=$keyboard 
          selected=1 
        else 
          dialog --backtitle "$titulo" --title "-| ERROR |-" --stdout --ok-label 'Siguiente' --msgbox "Ingrese una distribución del teclado para continuar" 5 55 
        fi
      done
        ;;
    esac
done




clear 
echo $keymap
echo $keymapx