#!/bin/bash

drivermanual () {

nombreGrafica=$(lspci | grep VGA |  awk -F " " '{print $5,$6,$7,$8,$9,$10}')

cmd=(dialog --nocancel --no-tags --backtitle "${title}" --title "-| Driver de Vídeo |-" \
    --menu "\nTarjeta de vídeo: \n\n${nombreGrafica}\n\nElige una opción\n " 14 60 00)

options=(   1 "  Video vesa (Generic All)             "
            2 "  Intel (Open Source)                  "
            3 "  AMD/ATI (Open Source)                "
            4 "  AMD/Radeon (Open Source)             "
            5 "  Nvidia (Open Source)                 "
            6 "  Nvidia + Intel (Open Source)         "
            7 "  Nvidia 495xx (Linux Stable)          "
            8 "  Nvidia 390xx (Linux Stable)          "
            9 "  Nvidia 495xx (Linux LTS)             "
            10 "  Nvidia 390xx (Linux LTS)             "
            11 "  Nvidia 495xx (Linux Hardened - Zen)  "
            12 "  Nvidia 390xx (Linux Hardened - Zen)  "
            13 "  Nvidia 495xx (Linux Stable + Intel)  ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)

for choice in $choices
do
    case $choice in


        1) video="Vesa OpenSource"
        ;;

        2) video="Intel OpenSource"
        ;;

        3) video="ATI OpenSource"
        ;;

        4) video="Radeon OpenSource"
        ;;

        5) video="Nvidia OpenSource"
        ;;

        6) video="Nvidia + Intel OpenSource"
        ;;

        7) video="Nvidia 495xx"
        ;;

        8) video="Nvidia 390xx"
        ;;

        9) video="Nvidia 495xx lts"
        ;;

        10) video="Nvidia 390xx lts"
        ;;

        11) video="Nvidia 495xx dkms"
        ;;

        12) video="Nvidia 390xx dkms"
        ;;

        13) video="Nvidia 495xx intel"
        ;;

    esac
done
}


driverautomatico () {

case $(systemd-detect-virt) in 
    oracle)

        if [ "$kernel_select" == "linux-stable" ]; then
        
            dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver virtualbox-host-modules-arch \n" 7 40
            video="VirtualBox"

        else

            dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver virtualbox-host-dkms \n" 7 35
            video="VirtualBox dkms"

        fi
    ;; 

    vmware)
        dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver xf86-video-vmware \n" 7 30
        video="VMware"
    ;; 

    qemu) 
        dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\nVídeo Detectado Qemu\n " 7 30
        video="Qemu"
    ;; 

    kvm) 
        dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\nVídeo Detectado Qemu kvm\n " 7 30
        video="Qemu Kvm"
    ;; 

    *)

if (lspci | grep VGA | grep "NVIDIA\|nVidia" &>/dev/null && lspci | grep VGA | grep "Intel" &>/dev/null); then 

dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver: xf86-video-intel xf86-video-nouveau mesa \n" 7 55
video="Nvidia + Intel OpenSource"

elif (lspci | grep VGA | grep "NVIDIA\|nVidia" &>/dev/null); then 

dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver: xf86-video-nouveau mesa \n" 7 37
video="Nvidia OpenSource"

elif (lspci | grep VGA | grep "Radeon R\|R2/R3/R4/R5" &>/dev/null); then 

dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver: xf86-video-amdgpu vulkan-radeon mesa \n" 7 50
video="Radeon OpenSource"


elif (lspci | grep VGA | grep "ATI\|AMD/ATI" &>/dev/null); then 

dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver: xf86-video-ati mesa \n" 7 33
video="ATI OpenSource"

elif (lspci | grep VGA | grep "Intel" &>/dev/null); then 

dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver: xf86-video-intel vulkan-intel mesa \n" 7 47
video="Intel OpenSource"

else

dialog --backtitle "${title}" --title "-| Vídeo |-" --stdout --ok-label 'Aceptar' --msgbox "\nDriver: xf86-video-vesa mesa \n" 7 0
video="Vesa OpenSource"

fi 

;; 
esac 

clear

}












drivervideo () {


if [[ ${sectionkernel} == "1" ]]; then

nombreGrafica=$(lspci | grep VGA |  awk -F " " '{print $5,$6,$7,$8,$9,$10}')

dialog --keep-tite --no-collapse --cr-wrap --backtitle "${title}" \
--title "-| Driver de Vídeo |-" --defaultno --yes-label '<  Manual  >' --no-label ' < Automático > ' \
--yesno "\nTarjeta de vídeo: \n\n${nombreGrafica}\n\nElige una opción\n " 00 00

respuestavideo=$?
case $respuestavideo in

   0) drivermanual ;;
   1) driverautomatico ;;
   255) echo "[ESC] key pressed.";;

esac

sectionvideo=1
current_item="8"

else

dialog --backtitle "${title}" --title "-| ERROR |-" --stdout --ok-label "< OK >"  --msgbox "\nSeleccione tu Kernel primero \n " 7 35
current_item="6"

fi




}





installvideo () {



case $video in 
    "Nvidia + Intel")



    ;; 

    vmware) 

    ;; 

    qemu) 

    ;; 

    kvm) 

    ;; 

    microsoft) 

    ;; 

    xen) 

    ;; 

    *)

    ;;


esac

}