#!/bin/bash

drivervideo () {

dialog --backtitle "${title}" \
--title "-| Información |-" \
--msgbox "----------------------------------------------------------------------\n \
\n> Si esta usando Maquina virtual la selección de Driver de Video es: \
\n  [Automatico] \n \
\n> Si esta usando Hardware real tiene dos opciones para seleccionar: \
\n  [Automatico] o [Manual] \n\n
----------------------------------------------------------------------\n\
\nMarca de tarjeta de vídeo: \n\n$(lspci | grep VGA |  awk -F " " '{print $5,$6,$7,$8,$9,$10,$11,$12,$13}')\n" 18 75


#Inicio de Video
virt=""
GPU=""
VM=false
VMbox=false
VMqemu=false

 ####################################################################
      
    case $(systemd-detect-virt) in
        oracle)
            virt="vbox"
            VM=true
        ;;
        vmware)
            virt="vmware"
            VM=true
        ;;
        qemu)
            virt="qemu"
            VM=true
        ;;
        kvm)
            virt="kvm"
            VM=true
        ;;
        microsoft)
            virt="hyper-v"
            VM=true
        ;;
        xen)
            virt="xen"
            VM=true
        ;;
    esac
    
    ####################################################################

# virtualbox-guest-utils xf86-video-vmware mesa lib32-mesa mesa-libgl 
# xf86-video-vesa mesa lib32-mesa mesa-libgl qemu-guest-agent

VMbox=false
if [ "$VM" == "true" ]; then
    
            infovideo
            case "$virt" in
                
                vbox)
                dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\n\nVídeo Detectado Virtual Box\n " 8 40                   
                ;;
                
                vmware)
                dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\n\nVídeo Detectado VMware\n " 8 40
                ;;
                
                hyper-v) 
                dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\n\nVídeo Detectado hyper-v\n " 8 40                         
                ;;
                
                qemu)
                dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\n\nVídeo Detectado Qemu\n " 8 40                   
                ;;

                kvm)  
                dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\n\nVídeo Detectado Qemu Kvm\n " 8 40                   
                ;;
                
                *)
                dialog --backtitle "${title}" --title "-| Driver de Vídeo |-" --stdout --ok-label "<Confirmar>"  --msgbox "\n\nVídeo Genérico Detectado Mesa\n " 8 45 
                ;;
                
            esac

            
else




}


