#!/bin/bash

#https://www.gsp.com/cgi-bin/man.cgi?section=1&topic=dialog

timezoneinfo () {

clear
curl https://ipapi.co/timezone > zoneinfo
zoneinfo=$(cat zoneinfo)
rm zoneinfo

dialog --backtitle "${title}" --title "${title_timezone}" --defaultno --yesno "\n       >>> $zoneinfo <<<\n\n       ${msg_timezone}" 8 40 

if [ "$?" = "0" ]; then

selected=0 
timezonedir=/usr/share/zoneinfo
while [ "$selected" = "0" ] 
do

  clear
  check=$(ls -l $timezonedir | grep -v .tab | awk '/drwx/' | awk -F " " '{print $9}' | awk '{if (NR!=1) {print}}' | head -1)
  if [[ $check != America ]]; then 
    echo "../ UP" >timezones 
  fi

  ls -l $timezonedir | grep -v .tab | awk '/drwx/' | awk -F " " '{print $9}' | awk '{print $0"/"}' | awk '$fs=$fs" Time"' | awk '{if (NR!=1) {print}}'>>timezones 
  
  ls -l $timezonedir | grep -v .tab | awk '/-rw-/' | awk -F " " '{print $9}' | awk '$fs=$fs" Time"' | awk '{if (NR!=1) {print}}'>>timezones
  timezones=$(cat timezones) 
  rm timezones 
  timezone=$(dialog --backtitle "| Instalación de ArchLinux |" --clear --title "Tu Zona Horaria es $(cat timezone): " \
      --menu "Ingresa la zona horaria" 20 0 20 ${timezones} 2>&1 >/dev/tty) 
  clear
  if [ "$?" = "0" ] 
  then
    if [[ $timezone == *"/"* ]]; then 
      timezonedir=$timezonedir/$timezone
    else 
      zonadefaultNo=true
      selected=1
    fi
  fi
done

else
#zone="$(cat timezone)"
zonadefaultYes=true
fi


}