#!/bin/bash

#https://www.gsp.com/cgi-bin/man.cgi?section=1&topic=dialog

timezoneinfo () {

zoneinfo="N/N"
clear
curl https://ipapi.co/timezone > zoneinfo
zoneinfo=$(cat zoneinfo)


dialog --backtitle "${title}" --title "${title_timezone}" --defaultno --yesno "\n       >>> $zoneinfo <<<\n\n       ${msg_timezone}" 9 40 

if [ "$?" = "0" ]; then

selected=0 
timezonedir=/usr/share/zoneinfo
while [ "$selected" = "0" ] 
do

  clear
  check=$(ls -l $timezonedir | grep -v .tab | awk '/drwx/' | awk -F " " '{print $9}' | awk '{if (NR!=1) {print}}' | head -1)
  if [[ $check != America ]]; then 
    echo "../ UP" >timezones 
  fi

  ls -l $timezonedir | grep -v .tab | awk '/drwx/' | awk -F " " '{print $9}' | awk '{print $0"/"}' | awk '$fs=$fs" Time"' | awk '{if (NR!=1) {print}}'>>timezones 
  
  ls -l $timezonedir | grep -v .tab | awk '/-rw-/' | awk -F " " '{print $9}' | awk '$fs=$fs" Time"' | awk '{if (NR!=1) {print}}'>>timezones
  
  zoneinfo=$(cat zoneinfo)
 
  timezone=$(dialog --backtitle "${title}" --title "${title_timezone}" --clear --title "${title_timezonemanual} $zoneinfo: " \
      --menu "${msg_timezonemanual}" 30 0 20 ${timezones} 2>&1 >/dev/tty) 
  clear
  if [ "$?" = "0" ] 
  then
    if [[ $timezone == *"/"* ]]; then 
      timezonedir=$timezonedir/$timezone
    else 
      zonadefaultNo=true
      selected=1
    fi
  fi
done

else
#zone="$(cat timezone)"
zonadefaultYes=true
fi

rm zoneinfo

}