#!/bin/bash

autopartition () {

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Particionado Automático del Disco |-" \
--no-tags --ok-label "Confirmar" --nocancel --menu "\nEliga su mejor opción para su Sistema\n " 13 55 11)
options=(1 " Root ( ext4 )                 "   
         2 " Root - Swap ( ext4 )          "
         3 " Root - Home ( ext4 )          "
		 4 " Root - Home - Swap ( ext4 )   ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
    ################

1) ################ 
sh partition/autoroot
;;

2) ################
shell="bash"
;;
3) ################
shell="fish"
;;

4) ################
shell="dash"
;;
                                                
    esac
done


}