#!/bin/bash

deletediskdd () {



################################################################
# SELETC DISK
################################################################

part="$(echo "print devices" | parted | grep /dev/ | awk '{if (NR!=1) {print}}' | sed '/sr/d')" 
disk=$(dialog --backtitle "${title}" --clear  --ok-label "Seleccionar disco" --no-cancel --menu "\nSelecciona el disco para formateado completo\n " 12 50 0 ${part} 2>&1 >/dev/tty)


dialog --no-collapse --cr-wrap --backtitle "$titulo" --title "-| Confirmar |-" --yesno "\nEsto suele demorar mucho tiempo dependiendo de la cantidad de GB de tu Disco seleccionado\n\n   ¿ Deseas continuar con formatear ?" 10 49

case $? in

   0)
#Desmontamos todo disco y swapoff
swapdisco=$( fdisk -l | grep "/dev/\|swap" | grep swap | awk -F ' ' '{print $1}' )
umount -R /mnt
clear
swapoff ${swapdisco}
clear
swapoff -a
clear
swapon -a
clear
rm /mnt/etc/fstab
clear 


bootarch=$( ls /sys/firmware/efi/ | grep -ic efivars )

case $bootarch in

  1)
dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Formateando Disco - UEFI |-" --stdout --ok-label "Siguiente" \
--prgbox "dd if=/dev/zero of="${disk}" bs=4M conv=fsync oflag=direct status=progress  && \
parted ${disk} mklabel gpt && \
fdisk -l ${disk} " 20 110
partprobe
clear
;;

  0)
dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Formateando Disco - BIOS LEGACY |-" --stdout --ok-label "Siguiente" \
--prgbox "dd if=/dev/zero of="${disk}" bs=4M conv=fsync oflag=direct status=progress  && \
parted ${disk} mklabel msdos && \
fdisk -l ${disk} " 20 110
partprobe
clear
;;

esac

;;

1) 
clear
;;
esac

}