#!/bin/bash

dualpartition () { 

#Desmontamos todo disco y swapoff
clear
rmmod floppy
swapdisco=$( fdisk -l | grep "/dev/\|swap" | grep swap | awk -F ' ' '{print $1}' )
umount -R /mnt
swapoff ${swapdisco}
clear
swapoff -a
swapon -a
rm /mnt/etc/fstab
clear 

part=""
disk=""
partitions=""
p=""
part=""
rootfs=""



bootarch=$( ls /sys/firmware/efi/ | grep -ic efivars )

### UEFII
if [[ $bootarch == 1 ]]; then  
  
echo " UEFI"

### BIOSSSSSS 
else  
  
part="$(echo "print devices" | parted | grep /dev/ | awk '{if (NR!=1) {print}}' | sed '/sr/d')" 
disk=$(dialog --backtitle "$titulo" --clear  --ok-label 'Seleccionar' --no-cancel --menu "Selecciona el disco para Linux" 10 50 0 ${part} 2>&1 >/dev/tty)


partitioner=$(dialog --backtitle "$titulo" --clear --title "-| Particionado de Disco |-" --ok-label 'Seleccionar' --no-cancel --menu ">\n> Crear particiones correctamente\n>" 9 0 0\
    "cfdisk" "Un particionador casi grafico" \
    "fdisk" "Un particionador de linea de comandos" \
    "parted" "Un particionador de linea de comandos" 2>&1 > /dev/tty)

$partitioner $disk

fdisk -l "$disk" > /tmp/partitions

partitions="$(cat /tmp/partitions | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1,$5}')"

p="$(echo "$partitions")"

part=$(dialog --backtitle "$titulo" --ok-label 'Seleccionar' --no-cancel --clear --menu "Selecciona la partición para Root: [ / ]" 15 60 0 ${p} 2>&1 > /dev/tty)

rootfs=$part


p=$(echo "$p" | grep -v $part)


fi



clear
partprobe

dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Informarción |-" --stdout --ok-label "Siguiente" \
--prgbox "lsblk -lo NAME,SIZE,MOUNTPOINT,TYPE > /tmp/partitions && \
echo -------------------------------------- && \
echo _ && \
cat /tmp/partitions && \
echo _ && \
echo --------------------------------------" 20 50


}