#!/bin/bash

dualpartition () { 

#Desmontamos todo disco y swapoff
clear
rmmod floppy
swapdisco=$( fdisk -l | grep "/dev/\|swap" | grep swap | awk -F ' ' '{print $1}' )
umount -R /mnt
swapoff ${swapdisco}
clear
swapoff -a
swapon -a
rm /mnt/etc/fstab
clear 

part=""
disk=""
partitions=""
p=""
part=""
rootfs=""


part="$(lsblk -lno NAME,SIZE,TYPE | grep 'disk' | awk '{print "/dev/" $1 " " $2}' | sort -u | sed '/f/d' | sed '/sr/d' )" 
disk=$(dialog --backtitle "${title}" --clear  --ok-label "Seleccionar disco" --no-cancel --menu "\nSelecciona el disco para Arch Linux\n " 12 45 0 ${part} 2>&1 >/dev/tty)

partitioner=$(dialog --backtitle "$titulo" --clear --title "-| Particionado de Disco |-" --ok-label 'Seleccionar' --no-cancel --menu ">\n> Crear particiones correctamente\n>" 9 0 0\
    "cfdisk" " Un particionador casi grafico         " \
    "fdisk " " Un particionador de linea de comandos " \
    "parted" " Un particionador de linea de comandos " 2>&1 > /dev/tty)

clear

$partitioner $disk

fdisk -l "$disk" > /tmp/partitions

#partitions="$(cat /tmp/partitions | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1,$5}')"
partitions=$(fdisk -l ${disk} | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1,$5}' | grep /dev/ | awk '{if (NR=1) {print}}' | sed 's/*//g')
p="$(echo "$partitions")"

part=$(dialog --backtitle "${title}" --title "-| Selección de puntos de Montaje |-" --ok-label 'Seleccionar' --no-cancel --clear \
  --menu "\nSelecciona la partición para Linux: \n " 10 55 0 ${p} 2>&1 > /dev/tty)

rootfs=$part

# bootwin=$(fdisk -l ${disk} | grep /dev/ | awk '{if (NR!=1) {print}}' | grep "*" | awk -F ' ' '{print $1}' )


mkfs.ext4 -F "$rootfs"
mount "$rootfs" /mnt


clear
partprobe

dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Informarción |-" --stdout --ok-label "Siguiente" \
--prgbox "lsblk -lo NAME,SIZE,MOUNTPOINT,TYPE > /tmp/partitions && \
echo -------------------------------------- && \
echo _ && \
cat /tmp/partitions && \
echo _ && \
echo --------------------------------------" 20 50


}





bootarch=$( ls /sys/firmware/efi/ | grep -ic efivars )

### UEFII
if [[ $bootarch == 1 ]]; then  
  
echo " UEFI"

### BIOSSSSSS 
else  

echo " BIOS"

fi





part="$(echo "print devices" | parted | grep /dev/ | awk '{if (NR!=1) {print}}' | sed '/sr/d')" 
disk=$(dialog --backtitle "$titulo" --clear  --ok-label 'Seleccionar' --no-cancel --menu "Selecciona el disco para Linux" 10 50 0 ${part} 2>&1 >/dev/tty)
