#!/bin/bash

tabledisk () {



################################################################
# SELETC DISK
################################################################

part="$(echo "print devices" | parted | grep /dev/ | awk '{if (NR!=1) {print}}' | sed '/sr/d')" 
disk=$(dialog --backtitle "${title}" --clear  --ok-label "Seleccionar disco" --no-cancel --menu "\nSelecciona el disco para formateado completo\n " 12 50 0 ${part} 2>&1 >/dev/tty)

bootarch=$( ls /sys/firmware/efi/ | grep -ic efivars )

if [[ $bootarch == 1 ]]; then
  tableboot="UEFI"
else
  tableboot="BIOS LEGACY"
fi

cmd=(dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Tabla de Partición |-" \
--ok-label "Confirmar" --no-tags --menu "\nBorrá toda información de su Disco\n- Para sistema UEFI use GPT\n- Para sistema BIOS LEGACY use MBR/dos\n\nTu sistema iniciado es : ${tableboot}\n " 15 50 15)
options=(1 "         Convertir disco a GPT                 "   
         2 "         Convertir disco a MBR-dos             ")

choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
    ################

1) ################ 
dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Preparando Disco - UEFI |-" --stdout --ok-label "Siguiente" \
--prgbox "sgdisk --zap-all ${disk} && \
parted ${disk} mklabel gpt && \
fdisk -l ${disk} > /tmp/partitions && \
echo -------------------------------------- && \
cat /tmp/partitions" 20 110

;;

2) ################ 
dialog --no-collapse --cr-wrap --backtitle "${title}" --title "-| Preparando Disco - UEFI |-" --stdout --ok-label "Siguiente" \
--prgbox "sgdisk --zap-all ${disk} && \
parted ${disk} mklabel msdos && \
fdisk -l ${disk} > /tmp/partitions && \
echo -------------------------------------- && \
cat /tmp/partitions" 20 110

;;

    esac
done




}